// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Epiq.ETS.TCMS.Anywhere.Testing.E2ETest.Features.Cases.Detail.Claims
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Case Detail - Claim - Claims New")]
    [NUnit.Framework.CategoryAttribute("NewClaimsFeature")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("DoNotExecute")]
    [NUnit.Framework.CategoryAttribute("RegressionFixesIt34")]
    public partial class CaseDetail_Claim_ClaimsNewFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CaseClaimsNew.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Case Detail - Claim - Claims New", "\tIn order to manage Claims for a Case\r\n\tAs a user of Unity with Claim Permissions" +
                    "\r\n\tI need to be able to create a New Claim", ProgrammingLanguage.CSharp, new string[] {
                        "NewClaimsFeature",
                        "RegressionFixesIt34"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("001 - Case Detail - Claims - New Claim - Form Layout")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112342")]
        [NUnit.Framework.CategoryAttribute("TC112344")]
        [NUnit.Framework.CategoryAttribute("TC112346")]
        [NUnit.Framework.CategoryAttribute("TC112347")]
        [NUnit.Framework.CategoryAttribute("US110864")]
        [NUnit.Framework.CategoryAttribute("TC112037")]
        [NUnit.Framework.CategoryAttribute("US110866")]
        [NUnit.Framework.CategoryAttribute("TC112207")]
        [NUnit.Framework.CategoryAttribute("TC112208")]
        [NUnit.Framework.CategoryAttribute("TC112209")]
        [NUnit.Framework.CategoryAttribute("TC112210")]
        [NUnit.Framework.CategoryAttribute("US110867")]
        [NUnit.Framework.CategoryAttribute("TC112110")]
        [NUnit.Framework.CategoryAttribute("TC112111")]
        [NUnit.Framework.CategoryAttribute("TC112112")]
        [NUnit.Framework.CategoryAttribute("TC112118")]
        [NUnit.Framework.CategoryAttribute("TC112055")]
        [NUnit.Framework.CategoryAttribute("US110870")]
        [NUnit.Framework.CategoryAttribute("TC112826")]
        [NUnit.Framework.CategoryAttribute("US110871")]
        [NUnit.Framework.CategoryAttribute("TC112810")]
        [NUnit.Framework.CategoryAttribute("US110873")]
        [NUnit.Framework.CategoryAttribute("TC112856")]
        [NUnit.Framework.CategoryAttribute("TC112857")]
        [NUnit.Framework.CategoryAttribute("US110874")]
        [NUnit.Framework.CategoryAttribute("TC112813")]
        [NUnit.Framework.CategoryAttribute("US110875")]
        [NUnit.Framework.CategoryAttribute("TC112845")]
        [NUnit.Framework.CategoryAttribute("TC112848")]
        [NUnit.Framework.CategoryAttribute("US110879")]
        [NUnit.Framework.CategoryAttribute("TC112495")]
        [NUnit.Framework.CategoryAttribute("TC112496")]
        [NUnit.Framework.CategoryAttribute("TC112497")]
        [NUnit.Framework.CategoryAttribute("TC112498")]
        [NUnit.Framework.CategoryAttribute("TC112499")]
        [NUnit.Framework.CategoryAttribute("TC112500")]
        public virtual void _001_CaseDetail_Claims_NewClaim_FormLayout()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("001 - Case Detail - Claims - New Claim - Form Layout", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110905",
                        "TC112342",
                        "TC112344",
                        "TC112346",
                        "TC112347",
                        "US110864",
                        "TC112037",
                        "US110866",
                        "TC112207",
                        "TC112208",
                        "TC112209",
                        "TC112210",
                        "US110867",
                        "TC112110",
                        "TC112111",
                        "TC112112",
                        "TC112118",
                        "TC112055",
                        "US110870",
                        "TC112826",
                        "US110871",
                        "TC112810",
                        "US110873",
                        "TC112856",
                        "TC112857",
                        "US110874",
                        "TC112813",
                        "US110875",
                        "TC112845",
                        "TC112848",
                        "US110879",
                        "TC112495",
                        "TC112496",
                        "TC112497",
                        "TC112498",
                        "TC112499",
                        "TC112500"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I See New Claim Button Displays on Summary Card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.When("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("I See New Claim Form Displays With Correct Layout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("002 - Case Detail - Claims - New Claim - Status Dropdown Selection Updates Corner" +
            " Tag")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112038")]
        [NUnit.Framework.CategoryAttribute("TC112039")]
        [NUnit.Framework.CategoryAttribute("TC112040")]
        [NUnit.Framework.CategoryAttribute("TC112041")]
        [NUnit.Framework.CategoryAttribute("TC112042")]
        public virtual void _002_CaseDetail_Claims_NewClaim_StatusDropdownSelectionUpdatesCornerTag()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("002 - Case Detail - Claims - New Claim - Status Dropdown Selection Updates Corner" +
                    " Tag", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110905",
                        "TC112038",
                        "TC112039",
                        "TC112040",
                        "TC112041",
                        "TC112042"});
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I See New Claim Button Displays on Summary Card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Status",
                        "Color"});
            table1.AddRow(new string[] {
                        "Valid To Pay",
                        "GREEN"});
            table1.AddRow(new string[] {
                        "Invalid",
                        "RED"});
            table1.AddRow(new string[] {
                        "Withdrawn",
                        "RED"});
            table1.AddRow(new string[] {
                        "Superseded",
                        "RED"});
#line 40
 testRunner.When("I Select Each Status The Corner Tag Color Updates", ((string)(null)), table1, "When ");
#line 47
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("003 - Case Detail - Claims - New Claim - Required Fields Validation Chapter 7")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("Validations")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112352")]
        [NUnit.Framework.CategoryAttribute("US110870")]
        [NUnit.Framework.CategoryAttribute("TC112832")]
        [NUnit.Framework.CategoryAttribute("US110875")]
        [NUnit.Framework.CategoryAttribute("TC112849")]
        [NUnit.Framework.TestCaseAttribute("Chapter 7", "03-30382", "Name,Code,Pay Sequence", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Chapter 7", "17-10001", "Name,Code,Pay Sequence", new string[0])]
        public virtual void _003_CaseDetail_Claims_NewClaim_RequiredFieldsValidationChapter7(string caseType, string caseNumber, string mandatoryFields, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "Validations",
                    "US110905",
                    "TC112352",
                    "US110870",
                    "TC112832",
                    "US110875",
                    "TC112849"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("003 - Case Detail - Claims - New Claim - Required Fields Validation Chapter 7", @__tags);
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.And(string.Format("I Enter to Case Detail page for Case with Case Number \'{0}\'", caseNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I See Save Button is inactive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.When(string.Format("I Enter Valid Data For {0} And I See Validation Messages Dissapear One At A Time", mandatoryFields), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.And("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.Then("I See Claim Form Has Been Closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.And("I See Claim Displays On The List", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("004 - Case Detail - Claims - New Claim - Name Is Predictive")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112354")]
        [NUnit.Framework.CategoryAttribute("TC112357")]
        [NUnit.Framework.CategoryAttribute("TC112361")]
        [NUnit.Framework.CategoryAttribute("TC112362")]
        [NUnit.Framework.TestCaseAttribute("ABBY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("12", new string[0])]
        [NUnit.Framework.TestCaseAttribute("DIANA", new string[0])]
        public virtual void _004_CaseDetail_Claims_NewClaim_NameIsPredictive(string nameText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110905",
                    "TC112354",
                    "TC112357",
                    "TC112361",
                    "TC112362"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("004 - Case Detail - Claims - New Claim - Name Is Predictive", @__tags);
#line 75
this.ScenarioSetup(scenarioInfo);
#line 76
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.When(string.Format("I Type \'{0}\' on Name Search Field", nameText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.Then("I See Claim Name Results Match Predictive Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("005 - Case Detail - Claims - New Claim - Name Add New Claimant")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112355")]
        [NUnit.Framework.CategoryAttribute("TC112363")]
        [NUnit.Framework.CategoryAttribute("TC112364")]
        [NUnit.Framework.CategoryAttribute("TC112365")]
        [NUnit.Framework.TestCaseAttribute("Test Adding a Claimant", new string[0])]
        public virtual void _005_CaseDetail_Claims_NewClaim_NameAddNewClaimant(string nameText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "US110905",
                    "TC112355",
                    "TC112363",
                    "TC112364",
                    "TC112365"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("005 - Case Detail - Claims - New Claim - Name Add New Claimant", @__tags);
#line 92
this.ScenarioSetup(scenarioInfo);
#line 93
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And(string.Format("I Type \'{0}\' on Name Search Field", nameText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.And("I Select Add Claimant Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.When(string.Format("I Type \'{0}\' on Name Search Field", nameText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
 testRunner.Then(string.Format("I See The Exact Result \'{0}\' As An Existent Name", nameText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("006 - Case Detail - Claims - New Claim Save")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112348")]
        [NUnit.Framework.CategoryAttribute("TC112349")]
        [NUnit.Framework.CategoryAttribute("TC112350")]
        [NUnit.Framework.CategoryAttribute("TC112351")]
        [NUnit.Framework.CategoryAttribute("TC112353")]
        [NUnit.Framework.CategoryAttribute("TC112367")]
        [NUnit.Framework.CategoryAttribute("TC112369")]
        [NUnit.Framework.TestCaseAttribute("", "Test Automation Claims Creation", "", "", "", "", "--", "", "100", "", "", "", "$0.00", "$0.00", "$0.00", "$0.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("369547", "Test Automation Claims Creation", "", "", "", "", "--", "", "100", "", "", "", "$0.00", "$0.00", "$0.00", "$0.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Automation", "Test Automation Claims Creation", "", "", "", "", "--", "", "100", "", "", "", "$0.00", "$0.00", "$0.00", "$0.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Automated 12", "Test Automation Claims Creation", "", "", "", "", "--", "", "100", "", "", "", "$0.00", "$0.00", "$0.00", "$0.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AUTO987651", "Test Automation Claims Creation", "", "", "", "", "--", "", "100", "", "", "", "$0.00", "$0.00", "$0.00", "$0.00", new string[0])]
        public virtual void _006_CaseDetail_Claims_NewClaimSave(
                    string number, 
                    string name, 
                    string status, 
                    string objectionCode, 
                    string category, 
                    string code, 
                    string @class, 
                    string subCode, 
                    string paySequence, 
                    string scheduled, 
                    string claimed, 
                    string allowed, 
                    string reserved, 
                    string interest, 
                    string paid, 
                    string balance, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110905",
                    "TC112348",
                    "TC112349",
                    "TC112350",
                    "TC112351",
                    "TC112353",
                    "TC112367",
                    "TC112369"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("006 - Case Detail - Claims - New Claim Save", @__tags);
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 114
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Number",
                        "Name",
                        "Status",
                        "Category",
                        "Code",
                        "Sub Code",
                        "Pay Sequence",
                        "Scheduled",
                        "Claimed",
                        "Allowed",
                        "Reserved"});
            table2.AddRow(new string[] {
                        string.Format("{0}", number),
                        string.Format("{0}", name),
                        string.Format("{0}", status),
                        string.Format("{0}", category),
                        string.Format("{0}", code),
                        string.Format("{0}", subCode),
                        string.Format("{0}", paySequence),
                        string.Format("{0}", scheduled),
                        string.Format("{0}", claimed),
                        string.Format("{0}", allowed),
                        string.Format("{0}", reserved)});
#line 117
 testRunner.And("I Enter These Values On Basic Claim Form", ((string)(null)), table2, "And ");
#line 120
 testRunner.And(string.Format("I See Calculated Values Update to \'{0}\' \'{1}\' \'{2}\' And \'{3}\'", @class, interest, paid, balance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
 testRunner.When("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REVIEW_FOR_APP_BUG_007 - Case Detail - Claims - New Claim - Save And Add Another")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112366")]
        public virtual void REVIEW_FOR_APP_BUG_007_CaseDetail_Claims_NewClaim_SaveAndAddAnother()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REVIEW_FOR_APP_BUG_007 - Case Detail - Claims - New Claim - Save And Add Another", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110905",
                        "TC112366"});
#line 155
this.ScenarioSetup(scenarioInfo);
#line 156
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 157
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I Enter A Valid Claim Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("I Enter A Valid Name Value For Test \'Save And Add Another\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.When("I Click On Save And Add Another Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 163
 testRunner.Then("I See Claim Displays On The List", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
 testRunner.And("I See New Claim Form Displays With Correct Layout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("008 - Case Detail - Claims - New Claim - Cancel")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110905")]
        [NUnit.Framework.CategoryAttribute("TC112368")]
        public virtual void _008_CaseDetail_Claims_NewClaim_Cancel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("008 - Case Detail - Claims - New Claim - Cancel", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110905",
                        "TC112368"});
#line 170
this.ScenarioSetup(scenarioInfo);
#line 171
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 172
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.And("I Enter A Valid Claim Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And("I Enter A Valid Name Value For Test \'Cancel\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.When("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 178
 testRunner.Then("I See Claim Does Not Display On The List", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 179
 testRunner.And("I See Claim Form Has Been Closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("009 - Case Detail - Claims - New Claim - Code Input Is Predictive")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110867")]
        [NUnit.Framework.CategoryAttribute("TC112113")]
        [NUnit.Framework.CategoryAttribute("TC112114")]
        [NUnit.Framework.CategoryAttribute("TC112115")]
        [NUnit.Framework.CategoryAttribute("TC112116")]
        [NUnit.Framework.TestCaseAttribute("2100", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2200", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Bond", new string[0])]
        [NUnit.Framework.TestCaseAttribute("accountant for trustee", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Chapter 7", new string[0])]
        public virtual void _009_CaseDetail_Claims_NewClaim_CodeInputIsPredictive(string code, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110867",
                    "TC112113",
                    "TC112114",
                    "TC112115",
                    "TC112116"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("009 - Case Detail - Claims - New Claim - Code Input Is Predictive", @__tags);
#line 184
this.ScenarioSetup(scenarioInfo);
#line 185
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 186
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.When(string.Format("I Type \'{0}\' on Code Field", code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 190
 testRunner.Then("I See Code Results Match Predictive Search And Display Correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("010 - Case Detail - Claims - New Claim - Code Selection Updates Class")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110867")]
        [NUnit.Framework.CategoryAttribute("TC112118")]
        [NUnit.Framework.CategoryAttribute("TC118119")]
        [NUnit.Framework.CategoryAttribute("TC112121")]
        [NUnit.Framework.TestCaseAttribute("2100", "2100 Chapter 7 - Other Trustee", "Administrative", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3721", "3721 Chapter 7 - Arbitrator/Mediator for Trustee Fees", "Administrative", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4300", "4300 Chapter 7 - Internal Revenue Service Tax Liens (pre-petition)", "Secured", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5200", "5200 Chapter 7 - Unsecured Claims Allowed Under 502(f) to 507(a)(2)", "Priority", new string[0])]
        [NUnit.Framework.TestCaseAttribute("6101", "6101 Chapter 7 - Trustee Compensation (Chapter 11)", "Administrative", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7300", "7300 Chapter 7 - Fines, Penalties726(a)(4)", "Unsecured", new string[0])]
        [NUnit.Framework.TestCaseAttribute("8200", "8200 Chapter 7 - Surplus Funds Paid to Debtor 726 (a)(6) (includes Payments to sh" +
            "areholders and limited partners)", "Unsecured", new string[0])]
        public virtual void _010_CaseDetail_Claims_NewClaim_CodeSelectionUpdatesClass(string exactCode, string expectedText, string @class, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110867",
                    "TC112118",
                    "TC118119",
                    "TC112121"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("010 - Case Detail - Claims - New Claim - Code Selection Updates Class", @__tags);
#line 203
this.ScenarioSetup(scenarioInfo);
#line 204
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 205
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14418\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And(string.Format("I Type \'{0}\' on Code Field", exactCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.When("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 210
 testRunner.Then(string.Format("I See Code Input Displays Selected Code And Description \'{0}\'", expectedText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 211
 testRunner.And(string.Format("I See Class Autocompletes To \'{0}\'", @class), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("011 - Case Detail - Claims - New Claim Subcode Input Is Predictive")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110867")]
        [NUnit.Framework.CategoryAttribute("TC112056")]
        [NUnit.Framework.TestCaseAttribute("46", "46 Management Company Fees (Chapter 7 , Operating 7, or 11)", new string[0])]
        [NUnit.Framework.TestCaseAttribute("72", "72 Administrative Post-Petition Wages (Operating 7 or Chapter 11)", new string[0])]
        public virtual void _011_CaseDetail_Claims_NewClaimSubcodeInputIsPredictive(string subcode, string expectedText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110867",
                    "TC112056"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("011 - Case Detail - Claims - New Claim Subcode Input Is Predictive", @__tags);
#line 227
this.ScenarioSetup(scenarioInfo);
#line 228
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 229
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And("I Type \'2690\' on Code Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And(string.Format("I Type \'{0}\' on Subcode Field", subcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("I See Subcode Results Match Predictive Search And Display Correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.When("I Select The First Result On Subcode Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
 testRunner.Then(string.Format("I See Subcode Input Displays Selected Subcode And Description \'{0}\'", expectedText), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 238
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("012 - Case Detail - Claims - New Claim - Code List Sorting")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US?")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _012_CaseDetail_Claims_NewClaim_CodeListSorting()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("012 - Case Detail - Claims - New Claim - Code List Sorting", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US?",
                        "TC?"});
#line 247
this.ScenarioSetup(scenarioInfo);
#line 248
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 249
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 251
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 252
 testRunner.When("I Type \'\' on Code Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 253
 testRunner.Then("I See Code Results Display Sorted Descending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 254
 testRunner.And("I See Subcode Input Is Inactive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 255
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("012 - Case Detail - Claims - New Claim - Subcode List Sorting")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US?")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _012_CaseDetail_Claims_NewClaim_SubcodeListSorting()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("012 - Case Detail - Claims - New Claim - Subcode List Sorting", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US?",
                        "TC?"});
#line 261
this.ScenarioSetup(scenarioInfo);
#line 262
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 263
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.When("I Type \'2690\' on Code Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 267
 testRunner.And("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.And("I Type \'11\' on Subcode Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.Then("I See Subcode Results Display Sorted Descending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 270
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("013 - Case Detail - Claims - New Claim - Claimed Amount Updates Allowed Amount")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110875")]
        [NUnit.Framework.CategoryAttribute("TC112846")]
        [NUnit.Framework.CategoryAttribute("TC112847")]
        public virtual void _013_CaseDetail_Claims_NewClaim_ClaimedAmountUpdatesAllowedAmount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("013 - Case Detail - Claims - New Claim - Claimed Amount Updates Allowed Amount", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110875",
                        "TC112846",
                        "TC112847"});
#line 275
this.ScenarioSetup(scenarioInfo);
#line 276
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 277
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 278
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 280
 testRunner.And("I See Allowed Amount Field Value Is \'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 281
 testRunner.And("I See Balance Value Is \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 282
 testRunner.When("I Enter \'54.75\' on Claimed Amount Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 283
 testRunner.Then("I See Allowed Amount Field Value Is \'$ 54.75\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 284
 testRunner.And("I See Balance Value Is \'$54.75\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 285
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("014 - Case Detail - Claims - New Claim - Pay Sequence Validations")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110870")]
        [NUnit.Framework.CategoryAttribute("TC112829")]
        [NUnit.Framework.CategoryAttribute("TC112830")]
        [NUnit.Framework.CategoryAttribute("TC112831")]
        [NUnit.Framework.TestCaseAttribute("01", "01", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123", "123", new string[0])]
        [NUnit.Framework.TestCaseAttribute("154", "154", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1234", "1234", new string[0])]
        [NUnit.Framework.TestCaseAttribute("9000", "9000", new string[0])]
        public virtual void _014_CaseDetail_Claims_NewClaim_PaySequenceValidations(string entered, string expected, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110870",
                    "TC112829",
                    "TC112830",
                    "TC112831"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("014 - Case Detail - Claims - New Claim - Pay Sequence Validations", @__tags);
#line 290
this.ScenarioSetup(scenarioInfo);
#line 291
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 292
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 293
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 294
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 295
 testRunner.When(string.Format("I Enter \'{0}\' on Pay Sequence Field", entered), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 296
 testRunner.Then(string.Format("I See Pay Sequence Value is \'{0}\'", expected), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 297
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("015 - Case Detail - Claims - New Claim (More Options) - Payment Options And Notes" +
            " Layout")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110882")]
        [NUnit.Framework.CategoryAttribute("TC112516")]
        [NUnit.Framework.CategoryAttribute("US110879")]
        [NUnit.Framework.CategoryAttribute("TC112503")]
        [NUnit.Framework.CategoryAttribute("US110893")]
        [NUnit.Framework.CategoryAttribute("TC112550")]
        [NUnit.Framework.CategoryAttribute("US110894")]
        [NUnit.Framework.CategoryAttribute("TC112557")]
        [NUnit.Framework.CategoryAttribute("US110896")]
        [NUnit.Framework.CategoryAttribute("TC112562")]
        [NUnit.Framework.CategoryAttribute("US110899")]
        [NUnit.Framework.CategoryAttribute("TC112568")]
        [NUnit.Framework.CategoryAttribute("US110891")]
        [NUnit.Framework.CategoryAttribute("TC112545")]
        [NUnit.Framework.CategoryAttribute("US110889")]
        [NUnit.Framework.CategoryAttribute("TC112542")]
        public virtual void _015_CaseDetail_Claims_NewClaimMoreOptions_PaymentOptionsAndNotesLayout()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("015 - Case Detail - Claims - New Claim (More Options) - Payment Options And Notes" +
                    " Layout", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110882",
                        "TC112516",
                        "US110879",
                        "TC112503",
                        "US110893",
                        "TC112550",
                        "US110894",
                        "TC112557",
                        "US110896",
                        "TC112562",
                        "US110899",
                        "TC112568",
                        "US110891",
                        "TC112545",
                        "US110889",
                        "TC112542"});
#line 320
this.ScenarioSetup(scenarioInfo);
#line 321
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 322
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 323
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 324
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 325
 testRunner.When("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("016 - Case Detail - Claims - New Claim (More Options) - Bar Date Values")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110891")]
        [NUnit.Framework.CategoryAttribute("TC112545")]
        [NUnit.Framework.CategoryAttribute("TC112546")]
        [NUnit.Framework.TestCaseAttribute("10-14868", "12/27/2010", new string[0])]
        [NUnit.Framework.TestCaseAttribute("08-21226", "04/21/2010", new string[0])]
        [NUnit.Framework.TestCaseAttribute("0:000-XXX", "01/16/2017", new string[0])]
        public virtual void _016_CaseDetail_Claims_NewClaimMoreOptions_BarDateValues(string caseNumber, string expectedBarDate, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110891",
                    "TC112545",
                    "TC112546"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("016 - Case Detail - Claims - New Claim (More Options) - Bar Date Values", @__tags);
#line 333
this.ScenarioSetup(scenarioInfo);
#line 334
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 335
 testRunner.And(string.Format("I Enter to Case Detail page for Case with Case Number \'{0}\'", caseNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 337
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 338
 testRunner.When("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 339
 testRunner.Then(string.Format("I See Bar Date Value Is \'{0}\'", expectedBarDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 341
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("017 - Case Detail - Claims - New Claim (More Options) - Payment Options Max Chars" +
            "")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110882")]
        [NUnit.Framework.CategoryAttribute("TC112517")]
        [NUnit.Framework.CategoryAttribute("US110879")]
        [NUnit.Framework.CategoryAttribute("TC112504")]
        [NUnit.Framework.CategoryAttribute("US110893")]
        [NUnit.Framework.CategoryAttribute("TC112551")]
        [NUnit.Framework.CategoryAttribute("US110894")]
        [NUnit.Framework.CategoryAttribute("TC112558")]
        [NUnit.Framework.CategoryAttribute("US110896")]
        [NUnit.Framework.CategoryAttribute("TC112563")]
        [NUnit.Framework.CategoryAttribute("US110899")]
        [NUnit.Framework.CategoryAttribute("TC112567")]
        public virtual void _017_CaseDetail_Claims_NewClaimMoreOptions_PaymentOptionsMaxChars()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("017 - Case Detail - Claims - New Claim (More Options) - Payment Options Max Chars" +
                    "", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110882",
                        "TC112517",
                        "US110879",
                        "TC112504",
                        "US110893",
                        "TC112551",
                        "US110894",
                        "TC112558",
                        "US110896",
                        "TC112563",
                        "US110899",
                        "TC112567"});
#line 360
this.ScenarioSetup(scenarioInfo);
#line 361
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 362
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 365
 testRunner.When("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 366
 testRunner.Then("I Can Enter A Max Of Fifty Characters on Creditor Account Number Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 367
 testRunner.And("I Can Enter A Max Of Characters on Check Description Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 368
 testRunner.And("I Can Enter A Max Of Three Alphanumeric Chars on Amended By", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 369
 testRunner.And("I Can Enter A Max Of Three Numeric Chars on Amended By Version", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 370
 testRunner.And("I Can Enter A Max Of Three Alphanumeric Chars on Amends", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
 testRunner.And("I Can Enter A Max Of Three Numeric Chars on Amends Version", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 372
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("018 - Case Detail - Claims - New Claim (More Options) - Payment Options Fold And " +
            "Unfold")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110879")]
        [NUnit.Framework.CategoryAttribute("TC112501")]
        [NUnit.Framework.CategoryAttribute("TC112501")]
        public virtual void _018_CaseDetail_Claims_NewClaimMoreOptions_PaymentOptionsFoldAndUnfold()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("018 - Case Detail - Claims - New Claim (More Options) - Payment Options Fold And " +
                    "Unfold", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110879",
                        "TC112501",
                        "TC112501"});
#line 378
this.ScenarioSetup(scenarioInfo);
#line 379
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 380
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 381
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 382
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 383
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 384
 testRunner.When("I Click on Payment Options Title Bar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 385
 testRunner.Then("I See Payment Options Section Is Hidden", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 386
 testRunner.And("I Click on Payment Options Title Bar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 387
 testRunner.Then("I See Payment Options Section Is Open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 388
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("019 - Case Detail - Claims - New Claim (More Options) - Claim Options")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110886")]
        [NUnit.Framework.CategoryAttribute("TC112523")]
        [NUnit.Framework.CategoryAttribute("TC112524")]
        [NUnit.Framework.CategoryAttribute("TC112525")]
        [NUnit.Framework.CategoryAttribute("TC112526")]
        [NUnit.Framework.CategoryAttribute("TC112527")]
        [NUnit.Framework.CategoryAttribute("TC112528")]
        [NUnit.Framework.CategoryAttribute("TC112529")]
        [NUnit.Framework.CategoryAttribute("TC112530")]
        [NUnit.Framework.CategoryAttribute("TC112531")]
        public virtual void _019_CaseDetail_Claims_NewClaimMoreOptions_ClaimOptions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("019 - Case Detail - Claims - New Claim (More Options) - Claim Options", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110886",
                        "TC112523",
                        "TC112524",
                        "TC112525",
                        "TC112526",
                        "TC112527",
                        "TC112528",
                        "TC112529",
                        "TC112530",
                        "TC112531"});
#line 393
this.ScenarioSetup(scenarioInfo);
#line 394
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 395
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 396
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 397
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 398
 testRunner.And("I Type \'5200\' on Code Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.And("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 400
 testRunner.When("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 401
 testRunner.Then("I Can Select And Unselect All Options Except For Wage Deduction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 402
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("020 - Case Detail - Claims - New Claim (More Options) - Wage Deduction Selection")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110886")]
        [NUnit.Framework.CategoryAttribute("TC112525")]
        [NUnit.Framework.TestCaseAttribute("2690", "True", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5300", "True", new string[0])]
        [NUnit.Framework.TestCaseAttribute("6950", "True", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7100", "True", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7200", "True", new string[0])]
        [NUnit.Framework.TestCaseAttribute("", "False", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3711", "False", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5200", "False", new string[0])]
        public virtual void _020_CaseDetail_Claims_NewClaimMoreOptions_WageDeductionSelection(string exactCode, string selected, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "NewClaim",
                    "Regression",
                    "US110886",
                    "TC112525"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("020 - Case Detail - Claims - New Claim (More Options) - Wage Deduction Selection", @__tags);
#line 408
this.ScenarioSetup(scenarioInfo);
#line 409
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 410
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 411
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 412
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 413
 testRunner.And(string.Format("I Type \'{0}\' on Code Field", exactCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 414
 testRunner.And("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 415
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 418
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("021 - Case Detail - Claims - New Claim (More Options) - Notes Fold And Unfold")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110901")]
        [NUnit.Framework.CategoryAttribute("TC112575")]
        public virtual void _021_CaseDetail_Claims_NewClaimMoreOptions_NotesFoldAndUnfold()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("021 - Case Detail - Claims - New Claim (More Options) - Notes Fold And Unfold", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110901",
                        "TC112575"});
#line 442
this.ScenarioSetup(scenarioInfo);
#line 443
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 444
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 445
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 446
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 447
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 448
 testRunner.When("I Click on Notes Title Bar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 449
 testRunner.Then("I See Notes Section Is Hidden", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 450
 testRunner.And("I Click on Notes Title Bar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 451
 testRunner.And("I See Notes Section Is Open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 452
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("022 - Case Detail - Claims - New Claim (More Options) - Register Note")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110901")]
        [NUnit.Framework.CategoryAttribute("TC112575")]
        public virtual void _022_CaseDetail_Claims_NewClaimMoreOptions_RegisterNote()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("022 - Case Detail - Claims - New Claim (More Options) - Register Note", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110901",
                        "TC112575"});
#line 458
this.ScenarioSetup(scenarioInfo);
#line 459
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 460
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 461
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 462
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 463
 testRunner.And("I Enter A Valid Claim Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 464
 testRunner.And("I Enter A Valid Name Value For Test \'Register Note\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 465
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 466
 testRunner.When(@"I Enter Claim Register Note Text 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 467
 testRunner.And("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 468
 testRunner.And("I Click On Edit For The Created Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 469
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 470
 testRunner.Then("I See Note Displays on Claims Register Note Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 471
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("023 - Case Detail - Claims - New Claim (More Options) - Internal Claim Note")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US110901")]
        [NUnit.Framework.CategoryAttribute("TC112575")]
        public virtual void _023_CaseDetail_Claims_NewClaimMoreOptions_InternalClaimNote()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("023 - Case Detail - Claims - New Claim (More Options) - Internal Claim Note", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US110901",
                        "TC112575"});
#line 476
this.ScenarioSetup(scenarioInfo);
#line 477
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 478
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 479
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 480
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 481
 testRunner.And("I Enter A Valid Claim Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 482
 testRunner.And("I Enter A Valid Name Value For Test \'Internal Claim Note\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 483
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 484
 testRunner.When(@"I Enter Internal Claim Note Text 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 485
 testRunner.And("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 486
 testRunner.And("I Click On Edit For The Created Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 487
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 488
 testRunner.Then("I See Note Displays on Internal Claim Note Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 489
 testRunner.And("I Click On Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("024 - Case Detail - Claims - New Claim Save (More Options)")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("NewClaim")]
        [NUnit.Framework.CategoryAttribute("Regression")]
        [NUnit.Framework.CategoryAttribute("US?")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _024_CaseDetail_Claims_NewClaimSaveMoreOptions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("024 - Case Detail - Claims - New Claim Save (More Options)", new string[] {
                        "CaseDetail",
                        "NewClaim",
                        "Regression",
                        "US?",
                        "TC?"});
#line 495
this.ScenarioSetup(scenarioInfo);
#line 496
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 497
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 498
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 499
 testRunner.And("I Click On New Claim Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 500
 testRunner.And("I Enter A Valid Claim Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 501
 testRunner.And("I Enter A Valid Name Value For Test \'Internal Claim Note\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 502
 testRunner.And("I Type \'2690\' on Code Field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 503
 testRunner.And("I Select The First Result On Code Dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 504
 testRunner.And("I Click On More Options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Check Description",
                        "Creditor Acc Number",
                        "Wage Deduction",
                        "Non-Compensable",
                        "Exclude from UFR",
                        "Non-discharged",
                        "Reaffirmed",
                        "Date Filed",
                        "Amends",
                        "Amends Version",
                        "Amended By",
                        "Amended By Version"});
            table3.AddRow(new string[] {
                        "Check Description",
                        "Creditor Acc Number",
                        "true",
                        "true",
                        "false",
                        "true",
                        "false",
                        "09/26/2016",
                        "ABC",
                        "123",
                        "DEF",
                        "456"});
#line 505
 testRunner.And("I Enter These Values On More Options Claim Form", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Register Note",
                        "Internal Note"});
            table4.AddRow(new string[] {
                        "New Claim Register Note",
                        "New Claim Internal Note"});
#line 508
 testRunner.And("I Enter These Values For Claim Notes", ((string)(null)), table4, "And ");
#line 511
 testRunner.When("I Click On Save Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 512
 testRunner.Then("I See Claim Displays On The List", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 513
 testRunner.And("I See Claim Form Has Been Closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
