// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Epiq.ETS.TCMS.Anywhere.Testing.E2ETest.Features.Cases.Detail.Banking.Deposits
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Case Detail - Banking - Deposit Closing Costs - Claims Links")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("DoNotExecute")]
    [NUnit.Framework.CategoryAttribute("BankingTransactions")]
    public partial class CaseDetail_Banking_DepositClosingCosts_ClaimsLinksFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CaseBanking_DepositClosingCostsLinks.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Case Detail - Banking - Deposit Closing Costs - Claims Links", "\tIn order to be able to balance transactions\r\n\tAs a User with Banking or Epiq Adm" +
                    "in Role only\r\n\tI want to be able to write a deposit with closing costs associate" +
                    "d to it", ProgrammingLanguage.CSharp, new string[] {
                        "Regression",
                        "BankingTransactions"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("001 - Case Detail - Banking - Deposits - Add Claim Link - Layout")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _001_CaseDetail_Banking_Deposits_AddClaimLink_Layout()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("001 - Case Detail - Banking - Deposits - Add Claim Link - Layout", new string[] {
                        "CaseDetail",
                        "BankingTransactions",
                        "DepositsClosingCosts",
                        "DepositsClaimslinks",
                        "US121352",
                        "TC?"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I See Deposit Claim Link Section Layout Is Correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.When("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("I See Labels For Claim Link Columns Are Correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("I See \'1\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I Search And Select Claim To Link On Row \'1\' By Claim Number \'10\' And Claim Name " +
                    "\'COMPTROLLER OF MARYLAND\' And Claim Code \'5800\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I See \'2\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("002 - Case Detail - Banking - Deposits - Add Claim Link - List Of Claims")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _002_CaseDetail_Banking_Deposits_AddClaimLink_ListOfClaims()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("002 - Case Detail - Banking - Deposits - Add Claim Link - List Of Claims", new string[] {
                        "CaseDetail",
                        "BankingTransactions",
                        "DepositsClosingCosts",
                        "DepositsClaimslinks",
                        "US121352",
                        "TC?"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("I See Claim Name Search Box Placeholder For Row \'1\' Is \'Find claim by claim #, cl" +
                    "aim Name, or code...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.And("I Click On Claim Search Box For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I See The List Of Claims Displays With Correct Layout On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I Search And Select Claim To Link On Row \'1\' By Claim Number \'10A\' And Claim Name" +
                    " \'COMPTROLLER OF MARYLAND\' And Claim Code \'5800\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("I See Claim Name Search Box Placeholder For Row \'2\' Is \'Find claim by claim #, cl" +
                    "aim Name, or code...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("I Click On Claim Search Box For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("I See The List Of Claims Displays With Correct Layout On Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("003 - Case Detail - Banking - Deposits - Add Claim Link - Filter Claims List Resu" +
            "lts")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("10", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", new string[0])]
        [NUnit.Framework.TestCaseAttribute("LICENSING MARYLAND DEPT. OF LABOR", new string[0])]
        [NUnit.Framework.TestCaseAttribute("STINSON MORRISON HECKER LLP", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2100", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5800", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7100", new string[0])]
        public virtual void _003_CaseDetail_Banking_Deposits_AddClaimLink_FilterClaimsListResults(string text, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClosingCosts",
                    "DepositsClaimslinks",
                    "US121352",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("003 - Case Detail - Banking - Deposits - Add Claim Link - Filter Claims List Resu" +
                    "lts", @__tags);
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.When("I Click On Claim Search Box For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.And(string.Format("I Enter Text \'{0}\' on Claim Search Box Filter For Row \'1\'", text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.Then(string.Format("I See Filtered Results Match Search Text \'{0}\'", text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("004 - Case Detail - Banking - Deposits - Add Deposits Link - Claims Filter With N" +
            "o Results")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _004_CaseDetail_Banking_Deposits_AddDepositsLink_ClaimsFilterWithNoResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("004 - Case Detail - Banking - Deposits - Add Deposits Link - Claims Filter With N" +
                    "o Results", new string[] {
                        "CaseDetail",
                        "BankingTransactions",
                        "DepositsClosingCosts",
                        "DepositsClaimslinks",
                        "US121352",
                        "TC?"});
#line 80
this.ScenarioSetup(scenarioInfo);
#line 81
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 82
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.When("I Click On Claim Search Box For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.And("I Enter Text \'Non Existent Claim\' on Claim Search Box Filter For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.Then("I See No Claims Results On The Grid And a Message Reading \'No Results Available\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("005 - Case Detail - Banking - Deposits - Add Claim Link - Claim Selection")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("10A", "COMPTROLLER OF MARYLAND", "5800", "Tab", "", "False", "", new string[0])]
        [NUnit.Framework.TestCaseAttribute("10A", "COMPTROLLER OF MARYLAND", "5800", "Click", "", "False", "", new string[0])]
        [NUnit.Framework.TestCaseAttribute("", "ROSE, CHERYL E.", "3110", "Tab", "", "False", "", new string[0])]
        [NUnit.Framework.TestCaseAttribute("", "ROSE, CHERYL E.", "3110", "Click", "", "False", "", new string[0])]
        public virtual void _005_CaseDetail_Banking_Deposits_AddClaimLink_ClaimSelection(string claim, string claimName, string claimCode, string method, string allocationDescr, string nonCompensable, string amount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClosingCosts",
                    "DepositsClaimslinks",
                    "US121352",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("005 - Case Detail - Banking - Deposits - Add Claim Link - Claim Selection", @__tags);
#line 95
this.ScenarioSetup(scenarioInfo);
#line 96
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.And("I Click On Claim Search Box For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.When(string.Format("I Select Claim To Link On Row \'1\' By Claim Number \'{0}\' And Claim Name \'{1}\' And " +
                        "Claim Code \'{2}\' Using Method \'{3}\'", claim, claimName, claimCode, method), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.Then("I See Claim Link Grid Closes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And(string.Format("I See Claim Link Row \'1\' With Claim # \'{0}\' Name \'{1}\' Code \'{2}\' Allocation Desc" +
                        "ription \'{3}\' Non-Compensable \'{4}\' And Amount \'{5}\'", claim, claimName, claimCode, allocationDescr, nonCompensable, amount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("006 - Case Detail - Banking - Deposits - Add Claim Link - Cannot Select Repeated " +
            "Claims")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121352")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("10B", "COMPTROLLER OF MARYLAND", "7100", new string[0])]
        [NUnit.Framework.TestCaseAttribute("16A", "INTERNAL REVENUE SERVICE", "5800", new string[0])]
        public virtual void _006_CaseDetail_Banking_Deposits_AddClaimLink_CannotSelectRepeatedClaims(string claim, string claimName, string claimCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClosingCosts",
                    "DepositsClaimslinks",
                    "US121352",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("006 - Case Detail - Banking - Deposits - Add Claim Link - Cannot Select Repeated " +
                    "Claims", @__tags);
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 122
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.And("I Click On Claim Search Box For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.When(string.Format("I Select Claim To Link On Row \'1\' By Claim Number \'{0}\' And Claim Name \'{1}\' And " +
                        "Claim Code \'{2}\' Using Method \'Click\'", claim, claimName, claimCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.And("I Click On Claim Search Box For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And(string.Format("I Enter Text \'{0}\' on Claim Search Box Filter For Row \'2\'", claimName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.Then(string.Format("I See No Claim Result On Row \'2\' Has Claim Number \'{0}\' And Claim Name \'{1}\' And " +
                        "Claim Code \'{2}\'", claim, claimName, claimCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("008 - Case Detail - Banking - Deposits - Add Closing Costs Link - Remove In Order" +
            "")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121398")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _008_CaseDetail_Banking_Deposits_AddClosingCostsLink_RemoveInOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("008 - Case Detail - Banking - Deposits - Add Closing Costs Link - Remove In Order" +
                    "", new string[] {
                        "CaseDetail",
                        "BankingTransactions",
                        "DepositsClaimslinks",
                        "US121398",
                        "TC?"});
#line 174
this.ScenarioSetup(scenarioInfo);
#line 175
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 176
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("I Select The First Claim To Link On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.When("I Click On Remove Icon For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 183
 testRunner.Then("I See \'1\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 184
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.And("I Click On Remove Icon For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.And("I See \'0\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.And("I See Add Claim Link Now Reads \'ADD CLAIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("009 - Case Detail - Banking - Deposits - Add Closing Costs Link - Remove From Mid" +
            "dle")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121398")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        public virtual void _009_CaseDetail_Banking_Deposits_AddClosingCostsLink_RemoveFromMiddle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("009 - Case Detail - Banking - Deposits - Add Closing Costs Link - Remove From Mid" +
                    "dle", new string[] {
                        "CaseDetail",
                        "BankingTransactions",
                        "DepositsClaimslinks",
                        "US121398",
                        "TC?"});
#line 192
this.ScenarioSetup(scenarioInfo);
#line 193
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 194
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I Select The First Claim To Link On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.And("I Select The First Claim To Link On Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.And("I Select The First Claim To Link On Row \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.And("I See \'4\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.When("I Click On Remove Icon For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 206
 testRunner.Then("I See \'3\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 207
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I Click On Remove Icon For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And("I See \'2\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.And("I Click On Remove Icon For Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.And("I See \'1\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("I See Add Claim Link Now Reads \'ADD ADDITIONAL CLAIM LINK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.And("I Click On Remove Icon For Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
 testRunner.And("I See \'0\' Claim Link Rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.And("I See Add Claim Link Now Reads \'ADD CLAIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("010 - Case Detail - Banking - Deposits - Add Closing Cost Link - SUM OF CLOSING C" +
            "OSTS")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimsLink")]
        [NUnit.Framework.CategoryAttribute("US121386")]
        [NUnit.Framework.TestCaseAttribute("Test Automation Claim Links Sum Of Allocation", "13", "VERIZON", "7100", "3", "CHASE BANK USA NA", "7100", new string[0])]
        public virtual void _010_CaseDetail_Banking_Deposits_AddClosingCostLink_SUMOFCLOSINGCOSTS(string payTo, string claim1, string claimName1, string claimCode1, string claim2, string claimName2, string claimCode2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClaimsLink",
                    "US121386"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("010 - Case Detail - Banking - Deposits - Add Closing Cost Link - SUM OF CLOSING C" +
                    "OSTS", @__tags);
#line 221
this.ScenarioSetup(scenarioInfo);
#line 222
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 223
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'10-14868\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 224
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.When("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 226
 testRunner.Then("I See SUM OF CLOSING COSTS Label is \'SUM OF CLOSING COST(S)\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 227
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
 testRunner.And(string.Format("I Search And Select Claim To Link On Row \'1\' By Claim Number \'{0}\' And Claim Name" +
                        " \'{1}\' And Claim Code \'{2}\'", claim1, claimName1, claimCode1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And(string.Format("I Search And Select Claim To Link On Row \'2\' By Claim Number \'{0}\' And Claim Name" +
                        " \'{1}\' And Claim Code \'{2}\'", claim2, claimName2, claimCode2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I Enter Claim Link Amount \'$200.00\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$200.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I Enter Claim Link Amount \'$300.00\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$300.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
 testRunner.And("I Enter Claim Link Amount \'$200.00\' On Row \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.And("I See SUM OF CLOSING COSTS Is \'$500.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("011 - Case Detail - Banking - Deposits - Add Non Claim Payee")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimslinks")]
        [NUnit.Framework.CategoryAttribute("US121388")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("NON CLAIM PAYEE # 1 TEST", "5800", "TEST ALLOCATION description #1", "False", "$123.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("NON CLAIM PAYEE # 1 TEST VERY LONG NAME WHAT DO YOU SEE", "7100", "Alloc Desc # 2", "False", "", new string[0])]
        public virtual void _011_CaseDetail_Banking_Deposits_AddNonClaimPayee(string name, string code, string allocationDescription, string nonCompensable, string amount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClosingCosts",
                    "DepositsClaimslinks",
                    "US121388",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("011 - Case Detail - Banking - Deposits - Add Non Claim Payee", @__tags);
#line 247
this.ScenarioSetup(scenarioInfo);
#line 248
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 249
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 251
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 252
 testRunner.When("I Click On ADD Non Claim Payee Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 253
 testRunner.Then("I See AdADD Non Claim Payee Link Text Reads \'ADD NON-CLAIM PAYEE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 254
 testRunner.And("See Non Claim Payee Name Placeholder For Row \'1\' Is \'Enter Payee Name...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 255
 testRunner.And("I See Non Claim Payee Code Placeholder For Row \'1\' Is \'Search...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 256
 testRunner.And("I See Non Claim Payee Link Row \'1\' With Name \'\' Code \'Search...\' Allocation Descr" +
                    "iption \'\' Non-Compensable \'False\' And Amount \'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.And(string.Format("I Enter Non Claim Payee Name \'{0}\' Code \'{1}\' And Amount \'{2}\' On Row \'1\'", name, code, amount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And(string.Format("I Enter Non Claim Payee Link Allocation Description \'{0}\' On Row \'1\'", allocationDescription), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And(string.Format("I Enter Non Claim Payee Link Non-Compensable \'{0}\' On Row \'1\'", nonCompensable), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.And(string.Format("I See Non Claim Payee Link Row \'1\' With Name \'{0}\' Code \'{1}\' Allocation Descript" +
                        "ion \'{2}\' Non-Compensable \'{3}\' And Amount \'{4}\'", name, code, allocationDescription, nonCompensable, amount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.And("I Click On ADD Non Claim Payee Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("See Non Claim Payee Name Placeholder For Row \'2\' Is \'Enter Payee Name...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
 testRunner.And("I See Non Claim Payee Code Placeholder For Row \'2\' Is \'Search...\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.And("I See Non Claim Payee Link Row \'2\' With Name \'\' Code \'Search...\' Allocation Descr" +
                    "iption \'\' Non-Compensable \'False\' And Amount \'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("012 - Case Detail - Banking - Deposits - Add Closing Cost Link - Gross Deposit vs" +
            " Net Deposit Validation")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("DepositsClaimsLink")]
        [NUnit.Framework.CategoryAttribute("US123058")]
        [NUnit.Framework.CategoryAttribute("CR121900")]
        [NUnit.Framework.TestCaseAttribute("$700.00", "$500.00", "$100.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("$700.00", "$700.00", "$100.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("$400.00", "$800.00", "$200.00", new string[0])]
        public virtual void _012_CaseDetail_Banking_Deposits_AddClosingCostLink_GrossDepositVsNetDepositValidation(string netDeposit, string grossDeposit, string amount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "DepositsClaimsLink",
                    "US123058",
                    "CR121900"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("012 - Case Detail - Banking - Deposits - Add Closing Cost Link - Gross Deposit vs" +
                    " Net Deposit Validation", @__tags);
#line 274
this.ScenarioSetup(scenarioInfo);
#line 275
testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 276
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 277
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 278
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
 testRunner.And("I Click On ADD Non Claim Payee Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 280
 testRunner.And(string.Format("I Enter Non Claim Payee Name \'\' Code \'\' And Amount \'{0}\' On Row \'1\'", amount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 281
 testRunner.And(string.Format("I Enter Net Deposit Amount \'{0}\'", netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 282
 testRunner.When(string.Format("I Enter Gross Deposit Amount \'{0}\'", grossDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 283
 testRunner.Then("I See Save Buttons Are Disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 284
 testRunner.And("I See an Alert Validation Message Reading \'Gross Deposit Does Not Equal Sum of Al" +
                    "location(s)\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("014 - Case Detail - Banking - Deposits - Save With Closing Cost Links")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("TransactionSaving")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("US123038")]
        [NUnit.Framework.CategoryAttribute("US110761")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("Test Automation For Saving With Closing Costs", "$250.00", "$500.00", "7", "R&R PROFESSIONAL RECOVERY", "7100", "$150.00", new string[0])]
        public virtual void _014_CaseDetail_Banking_Deposits_SaveWithClosingCostLinks(string payTo, string netDeposit, string grossDeposit, string claim, string claimName, string claimCode, string claimAmount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "TransactionSaving",
                    "DepositsClosingCosts",
                    "US123038",
                    "US110761",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("014 - Case Detail - Banking - Deposits - Save With Closing Cost Links", @__tags);
#line 301
this.ScenarioSetup(scenarioInfo);
#line 302
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 304
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 305
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 306
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 307
 testRunner.And(string.Format("I Enter Deposit Received From Value \'{0}\'", payTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 308
 testRunner.And("I Click On ADD Non Claim Payee Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 309
 testRunner.And("I Enter Non Claim Payee Name \'Non Claim Payee Save Test\' Code \'7100\' And Amount \'" +
                    "$100.00\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 310
 testRunner.And("I Enter Non Claim Payee Link Allocation Description \'NonClaim Payee Description\' " +
                    "On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 311
 testRunner.And("I Enter Non Claim Payee Link Non-Compensable \'True\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 313
 testRunner.And(string.Format("I Search And Select Claim To Link On Row \'2\' By Claim Number \'{0}\' And Claim Name" +
                        " \'{1}\' And Claim Code \'{2}\'", claim, claimName, claimCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 314
 testRunner.And(string.Format("I Enter Claim Link Amount \'{0}\' On Row \'2\'", claimAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 315
 testRunner.And(string.Format("I Enter Net Deposit Amount \'{0}\'", netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 316
 testRunner.And(string.Format("I Enter Gross Deposit Amount \'{0}\'", grossDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 317
 testRunner.When("I Click On Save Deposit For Save With Links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 318
 testRunner.Then(string.Format("I See The Transaction Displays Data Correctly On Transactions List \'{0}\',\'SPLIT\'," +
                        "\'{1}\',\'\',\'\',\'\',\'\',\'\',\'\'", payTo, netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("013 - Case Detail - Banking - Deposits - Save With Assets Links And verify Assets" +
            " Display on Ledger (Enter Assets Disordered)")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("TransactionSaving")]
        [NUnit.Framework.CategoryAttribute("DepositsAssets")]
        [NUnit.Framework.CategoryAttribute("US123038")]
        [NUnit.Framework.CategoryAttribute("US110761")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("Test Automation Saving With Assets Links", "$300.00", "$300.00", "8", "BUSINESS CHECKING ACCOUNT (NEWWAVE SOLUTIONS, LLC)", "1121", "$100.00", "1", "Adv. Proc. #07-00402", "", "$200.00", new string[0])]
        public virtual void _013_CaseDetail_Banking_Deposits_SaveWithAssetsLinksAndVerifyAssetsDisplayOnLedgerEnterAssetsDisordered(string payTo, string netDeposit, string grossDeposit, string asset1, string assetName1, string assetCode1, string assetAmount1, string asset2, string assetName2, string assetCode2, string assetAmount2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "TransactionSaving",
                    "DepositsAssets",
                    "US123038",
                    "US110761",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("013 - Case Detail - Banking - Deposits - Save With Assets Links And verify Assets" +
                    " Display on Ledger (Enter Assets Disordered)", @__tags);
#line 332
this.ScenarioSetup(scenarioInfo);
#line 333
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 335
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 337
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 338
 testRunner.And(string.Format("I Enter Deposit Received From Value \'{0}\'", payTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 339
 testRunner.And(string.Format("I Enter Net Deposit Amount \'{0}\'", netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 340
 testRunner.And(string.Format("I Enter Gross Deposit Amount \'{0}\'", grossDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 341
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 342
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'1\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset1, assetName1, assetCode1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 343
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'1\'", assetAmount1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 344
 testRunner.And("I Enter Asset Fully Administered Date \'Today\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 345
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 346
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'2\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset2, assetName2, assetCode2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 347
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'2\'", assetAmount2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 348
 testRunner.When("I Click On Save Deposit For Save With Links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("013 - Case Detail - Banking - Deposits - Save With Assets Links And verify Assets" +
            " Display on Ledger (Enter Assets Ordered)")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("TransactionSaving")]
        [NUnit.Framework.CategoryAttribute("DepositsAssets")]
        [NUnit.Framework.CategoryAttribute("US123038")]
        [NUnit.Framework.CategoryAttribute("US110761")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("Test Automation Saving With Assets Links Entered In Order", "$300.00", "$300.00", "1", "Adv. Proc. #07-00402", "", "$200.00", "8", "BUSINESS CHECKING ACCOUNT (NEWWAVE SOLUTIONS, LLC)", "1121", "$100.00", new string[0])]
        public virtual void _013_CaseDetail_Banking_Deposits_SaveWithAssetsLinksAndVerifyAssetsDisplayOnLedgerEnterAssetsOrdered(string payTo, string netDeposit, string grossDeposit, string asset1, string assetName1, string assetCode1, string assetAmount1, string asset2, string assetName2, string assetCode2, string assetAmount2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "TransactionSaving",
                    "DepositsAssets",
                    "US123038",
                    "US110761",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("013 - Case Detail - Banking - Deposits - Save With Assets Links And verify Assets" +
                    " Display on Ledger (Enter Assets Ordered)", @__tags);
#line 360
this.ScenarioSetup(scenarioInfo);
#line 361
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 363
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 365
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 366
 testRunner.And(string.Format("I Enter Deposit Received From Value \'{0}\'", payTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 367
 testRunner.And(string.Format("I Enter Net Deposit Amount \'{0}\'", netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 368
 testRunner.And(string.Format("I Enter Gross Deposit Amount \'{0}\'", grossDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 369
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 370
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'1\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset1, assetName1, assetCode1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'1\'", assetAmount1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 372
 testRunner.And("I Enter Asset Fully Administered Date \'10/27/2016\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 373
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 374
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'2\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset2, assetName2, assetCode2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 375
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'2\'", assetAmount2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 376
 testRunner.When("I Click On Save Deposit For Save With Links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("015 - Case Detail - Banking - Deposits - Save With Assets And Closing Costs Links" +
            "")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("BankingTransactions")]
        [NUnit.Framework.CategoryAttribute("TransactionSaving")]
        [NUnit.Framework.CategoryAttribute("DepositsClosingCosts")]
        [NUnit.Framework.CategoryAttribute("DepositsAssets")]
        [NUnit.Framework.CategoryAttribute("US123038")]
        [NUnit.Framework.CategoryAttribute("US110761")]
        [NUnit.Framework.CategoryAttribute("TC?")]
        [NUnit.Framework.TestCaseAttribute("Test Automation Saving With Assets Links", "$950.00", "$1200.00", "8", "BUSINESS CHECKING ACCOUNT (NEWWAVE SOLUTIONS, LLC)", "1121", "$1,000.00", "1", "Adv. Proc. #07-00402", "", "$200.00", "2", "AMERICAN GENERAL", "4110", "$100.00", "$150.00", new string[0])]
        public virtual void _015_CaseDetail_Banking_Deposits_SaveWithAssetsAndClosingCostsLinks(
                    string payTo, 
                    string netDeposit, 
                    string grossDeposit, 
                    string asset1, 
                    string assetName1, 
                    string assetCode1, 
                    string assetAmount1, 
                    string asset2, 
                    string assetName2, 
                    string assetCode2, 
                    string assetAmount2, 
                    string claim, 
                    string claimName, 
                    string claimCode, 
                    string claimAmount, 
                    string nonClaimAmount, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CaseDetail",
                    "BankingTransactions",
                    "TransactionSaving",
                    "DepositsClosingCosts",
                    "DepositsAssets",
                    "US123038",
                    "US110761",
                    "TC?"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("015 - Case Detail - Banking - Deposits - Save With Assets And Closing Costs Links" +
                    "", @__tags);
#line 389
this.ScenarioSetup(scenarioInfo);
#line 390
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 392
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 393
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 394
 testRunner.And("I Click on Deposit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 395
 testRunner.And(string.Format("I Enter Deposit Received From Value \'{0}\'", payTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 396
 testRunner.And(string.Format("I Enter Net Deposit Amount \'{0}\'", netDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 397
 testRunner.And(string.Format("I Enter Gross Deposit Amount \'{0}\'", grossDeposit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 398
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'1\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset1, assetName1, assetCode1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 400
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'1\'", assetAmount1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 402
 testRunner.And("I Enter Asset Fully Administered Date \'10/27/2016\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 403
 testRunner.And("I Click On ADD Asset Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 404
 testRunner.And(string.Format("I Search And Select Asset To Link On Row \'2\' By Asset Number \'{0}\' And Asset Name" +
                        " \'{1}\' And Asset Code \'{2}\'", asset2, assetName2, assetCode2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 405
 testRunner.And(string.Format("I Enter Asset Linked Amount \'{0}\' On Row \'2\'", assetAmount2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 406
 testRunner.And("I Click On ADD Non Claim Payee Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 407
 testRunner.And(string.Format("I Enter Non Claim Payee Name \'Non Claim Payee Save Test\' Code \'7100\' And Amount \'" +
                        "{0}\' On Row \'1\'", nonClaimAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 408
 testRunner.And("I Enter Non Claim Payee Link Allocation Description \'NonClaim Payee Description\' " +
                    "On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 409
 testRunner.And("I Enter Non Claim Payee Link Non-Compensable \'True\' On Row \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 410
 testRunner.And("I Click On ADD Claim Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 411
 testRunner.And(string.Format("I Search And Select Claim To Link On Row \'2\' By Claim Number \'{0}\' And Claim Name" +
                        " \'{1}\' And Claim Code \'{2}\'", claim, claimName, claimCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 412
 testRunner.And(string.Format("I Enter Claim Link Amount \'{0}\' On Row \'2\'", claimAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 413
 testRunner.When("I Click On Save Deposit For Save With Links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 414
 testRunner.Then(string.Format("I See The Transaction Displays Data Correctly On Transactions List \'{0}\',\'SPLIT\'," +
                        "\'{1}\',\'{2}\',\'{3}\',\'{4}\',\'{5}\',\'{6}\',\'{7}\'", payTo, netDeposit, asset2, assetName2, assetAmount2, asset1, assetName1, assetAmount1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
