// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Epiq.ETS.TCMS.Anywhere.Testing.E2ETest.Features.Cases.Detail.Banking.Deposits
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CaseBanking_Deposits - Add Asset Link")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("DoNotExecute")]
    [NUnit.Framework.CategoryAttribute("BankingTransactions")]
    public partial class CaseBanking_Deposits_AddAssetLinkFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CaseBanking_Deposits_AddAssetLink.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CaseBanking_Deposits - Add Asset Link", null, ProgrammingLanguage.CSharp, new string[] {
                        "Regression",
                        "BankingTransactions"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("010_\"GrossDepositField\" Verify Gross Deposit field can be edited")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("deleteDepositForCase1960")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US121340")]
        [NUnit.Framework.CategoryAttribute("DoNotExecute")]
        [NUnit.Framework.CategoryAttribute("RegressionFixesNeeded")]
        public virtual void _010_GrossDepositFieldVerifyGrossDepositFieldCanBeEdited()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("010_\"GrossDepositField\" Verify Gross Deposit field can be edited", new string[] {
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "AssetsPage",
                        "deleteDepositForCase1960",
                        "AssetsPage",
                        "AssetsPage",
                        "US121340",
                        "DoNotExecute",
                        "RegressionFixesNeeded",
                        "Ignore"});
#line 169
this.ScenarioSetup(scenarioInfo);
#line 170
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 171
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("Enter Net Deposit value \'100\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.When("Enter Gross Deposit value \'50\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 176
 testRunner.Then("Verify Gross Deposit field value is not equal to entered Net Deposit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("011_\"GrossDepositField\" Verify Gross Deposit field can be filled before Net Depos" +
            "it field")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US121340")]
        public virtual void _011_GrossDepositFieldVerifyGrossDepositFieldCanBeFilledBeforeNetDepositField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("011_\"GrossDepositField\" Verify Gross Deposit field can be filled before Net Depos" +
                    "it field", new string[] {
                        "AssetsPage",
                        "US121340"});
#line 180
this.ScenarioSetup(scenarioInfo);
#line 181
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 182
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.When("Enter Gross Deposit value \'50\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
 testRunner.Then("Verify Gross Deposit field value is not equal to entered Net Deposit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("012_\"GrossDepositField\" Verify Gross Deposit field is not updated")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US121340")]
        public virtual void _012_GrossDepositFieldVerifyGrossDepositFieldIsNotUpdated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("012_\"GrossDepositField\" Verify Gross Deposit field is not updated", new string[] {
                        "AssetsPage",
                        "US121340"});
#line 190
this.ScenarioSetup(scenarioInfo);
#line 191
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 192
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.And("Enter Gross Deposit value \'50\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.And("Enter Net Deposit value \'100\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.Then("Verify Gross Deposit field value is not equal to entered Net Deposit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("013_\"GrossDepositField\" Verify Gross Deposit field is not updated")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US121340")]
        public virtual void _013_GrossDepositFieldVerifyGrossDepositFieldIsNotUpdated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("013_\"GrossDepositField\" Verify Gross Deposit field is not updated", new string[] {
                        "AssetsPage",
                        "US121340"});
#line 201
this.ScenarioSetup(scenarioInfo);
#line 202
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 203
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("Enter Gross Deposit value \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.When("Enter Net Deposit value \'100\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("014_\"SumOfAllocation\" Verify Sum Of Allocation label is updated with Linked Amoun" +
            "t values")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US121341")]
        public virtual void _014_SumOfAllocationVerifySumOfAllocationLabelIsUpdatedWithLinkedAmountValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("014_\"SumOfAllocation\" Verify Sum Of Allocation label is updated with Linked Amoun" +
                    "t values", new string[] {
                        "AssetsPage",
                        "US121341"});
#line 212
this.ScenarioSetup(scenarioInfo);
#line 213
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 214
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 217
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("Enter Linked Amount value \'50\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.And("Click on Add Additional Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
 testRunner.And("Search and Select Asset Link with value \'9\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 222
 testRunner.And("Enter Linked Amount value \'50\' for Asset Number \'9\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 223
 testRunner.And("Verify SUM OF ALLOCATION displays correct value \'$100.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 224
 testRunner.And("Remove Asset Link with Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.When("Remove Asset Link with Asset Number \'9\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 226
 testRunner.Then("Verify SUM OF ALLOCATION displays correct value \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("015_\"LinkedAmountGrossDeposit\" Verify first asset link Linked amount is equal to " +
            "Gross Deposit")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US126982")]
        public virtual void _015_LinkedAmountGrossDepositVerifyFirstAssetLinkLinkedAmountIsEqualToGrossDeposit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("015_\"LinkedAmountGrossDeposit\" Verify first asset link Linked amount is equal to " +
                    "Gross Deposit", new string[] {
                        "AssetsPage",
                        "US126982"});
#line 230
this.ScenarioSetup(scenarioInfo);
#line 231
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 232
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("Enter Gross Deposit value \'500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.When("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 238
 testRunner.Then("Verify Linked Amount value displayed is \'$ 500.00\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("016_\"LinkedAmountGrossDeposit\" Verify linked amount is not updated if Gross Depos" +
            "it is updated")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US126982")]
        public virtual void _016_LinkedAmountGrossDepositVerifyLinkedAmountIsNotUpdatedIfGrossDepositIsUpdated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("016_\"LinkedAmountGrossDeposit\" Verify linked amount is not updated if Gross Depos" +
                    "it is updated", new string[] {
                        "AssetsPage",
                        "US126982"});
#line 242
this.ScenarioSetup(scenarioInfo);
#line 243
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 244
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 245
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
 testRunner.And("Enter Gross Deposit value \'500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 248
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 249
 testRunner.And("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
 testRunner.When("Enter Gross Deposit value \'250\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.Then("Verify Linked Amount value displayed is \'$ 500.00\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("017_\"LinkedAmountGrossDeposit\" Verify if 2 asset link linked amount is Gross Depo" +
            "sit less linked amounts")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US126982")]
        [NUnit.Framework.CategoryAttribute("RegressionFixesIt34")]
        public virtual void _017_LinkedAmountGrossDepositVerifyIf2AssetLinkLinkedAmountIsGrossDepositLessLinkedAmounts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("017_\"LinkedAmountGrossDeposit\" Verify if 2 asset link linked amount is Gross Depo" +
                    "sit less linked amounts", new string[] {
                        "AssetsPage",
                        "US126982",
                        "RegressionFixesIt34"});
#line 256
this.ScenarioSetup(scenarioInfo);
#line 257
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 258
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.And("Enter Gross Deposit value \'500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
 testRunner.And("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.And("Enter Linked Amount value \'250\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("Click on Add Additional Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.And("Search and Select Asset Link with value \'1\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.Then("Verify Linked Amount value displayed is \'$ 250.00\' for Asset Number \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("018_\"LinkedAmountGrossDeposit\" Verify if equation is negative then next asset lin" +
            "k linked amount is 0")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US126982")]
        public virtual void _018_LinkedAmountGrossDepositVerifyIfEquationIsNegativeThenNextAssetLinkLinkedAmountIs0()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("018_\"LinkedAmountGrossDeposit\" Verify if equation is negative then next asset lin" +
                    "k linked amount is 0", new string[] {
                        "AssetsPage",
                        "US126982"});
#line 271
this.ScenarioSetup(scenarioInfo);
#line 272
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 273
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 275
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
 testRunner.And("Enter Gross Deposit value \'500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 277
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 278
 testRunner.And("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
 testRunner.And("Enter Linked Amount value \'600\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 280
 testRunner.And("Click on Add Additional Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 281
 testRunner.And("Search and Select Asset Link with value \'1\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 282
 testRunner.Then("Verify Linked Amount value displayed is \'$ 0.00\' for Asset Number \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("019_\"LinkedAmountGrossDeposit\" Verify first asset link behavior when removing and" +
            " adding it or different Gross Deposit")]
        [NUnit.Framework.CategoryAttribute("AssetsPage")]
        [NUnit.Framework.CategoryAttribute("US126982")]
        public virtual void _019_LinkedAmountGrossDepositVerifyFirstAssetLinkBehaviorWhenRemovingAndAddingItOrDifferentGrossDeposit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("019_\"LinkedAmountGrossDeposit\" Verify first asset link behavior when removing and" +
                    " adding it or different Gross Deposit", new string[] {
                        "AssetsPage",
                        "US126982"});
#line 286
this.ScenarioSetup(scenarioInfo);
#line 287
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 288
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'JAMES CAMERON MARR\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 289
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 290
 testRunner.And("Click to open Transaction with name \'Deposit\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 291
 testRunner.And("Enter Gross Deposit value \'500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 292
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 293
 testRunner.And("Search and Select Asset Link with value \'8\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 294
 testRunner.And("Verify Linked Amount value displayed is \'$ 500.00\' for Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 295
 testRunner.And("Remove Asset Link with Asset Number \'8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 296
 testRunner.And("Enter Gross Deposit value \'1200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 297
 testRunner.And("Click on Add Asset Link button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
 testRunner.And("Search and Select Asset Link with value \'1\' in column \'Asset Number\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 299
 testRunner.Then("Verify Linked Amount value displayed is \'$ 1,200.00\' for Asset Number \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
