// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Epiq.ETS.TCMS.Anywhere.Testing.E2ETest.Features.Claims
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ClaimsMangement")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("ReactJS")]
    [NUnit.Framework.CategoryAttribute("FailureCasesClaims")]
    public partial class ClaimsMangementFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ClaimsMangement.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ClaimsMangement", "Navigating to the different sections under Claims Mangement Page\r\nAdding and edit" +
                    "ing of claims", ProgrammingLanguage.CSharp, new string[] {
                        "Regression",
                        "ReactJS",
                        "FailureCasesClaims"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("001 - ClaimsMangement Page BreadCrumb Verification")]
        [NUnit.Framework.CategoryAttribute("US#259326")]
        [NUnit.Framework.CategoryAttribute("US#197601")]
        public virtual void _001_ClaimsMangementPageBreadCrumbVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("001 - ClaimsMangement Page BreadCrumb Verification", new string[] {
                        "US#259326",
                        "US#197601"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.Then("\'Claims Management\' page should be display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.Then("\'DashboardClaims\' Breadcrumb should display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
 testRunner.And("Table data should be present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("\'DEBTOR\' should be able sorted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("Page count should be display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("pagination shouold be display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("002 - Claims filters funnel Search and Clear")]
        [NUnit.Framework.CategoryAttribute("US#199846")]
        [NUnit.Framework.CategoryAttribute("US#199846")]
        public virtual void _002_ClaimsFiltersFunnelSearchAndClear()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("002 - Claims filters funnel Search and Clear", new string[] {
                        "US#199846",
                        "US#199846"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.When("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.When("I enter Creditor \'BRENT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.And("I select Class \'Unsecured\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I select Claim status \'Valid To Pay\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I enter Balance from \'0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I enter Balance to \'0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I select Case status \'All\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("Selected result should contains \'BRENT\' \'Unsecured\' \'0.00\' \'0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.When("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.And("Click on reset", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.Then("default data should be present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("003- Add Claim:Existing claimant")]
        [NUnit.Framework.CategoryAttribute("US199848")]
        public virtual void _003_AddClaimExistingClaimant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("003- Add Claim:Existing claimant", new string[] {
                        "US199848"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.When("I click on Add Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("I see subheader as \'Add Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
 testRunner.Then("I input case/debtor details as \'CASE # / DEBTOR NAME@11-18811 / EXECUTIVE DRYWALL" +
                    ", INC.;CATEGORY@Creditor;CLAIM #@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
    testRunner.When("I select Participant Type as \'Existing Claimant\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("I search claim \'SEARCH CLAIM / CREDITOR NAME@ALBAN TRACTOR CO., INC.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.Then("I input codesvalues information \'STATUS@Valid To Pay;OBJECTION CODE@Duplicate;UTC" +
                    " CODE@2100 Other Trustee\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.Then("I input codesvalues Amounts information \'SCHEDULED AMOUNT@100;CLAIMED AMOUNT@200;" +
                    "ALLOWED AMOUNT@300;RESERVED AMOUNT@400\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.Then("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@123456;CHE" +
                    "CK DESCRIPTION@DESCRPTION;DATE FILED@01/30/19;AMENDS@TEST;VERSION@12;AMENDED BY@" +
                    "TEST;AMENDED VERSION@12\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
 testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@TEST;INTERNAL CLAIM NOTE@NOTE2;OB" +
                    "JECTION NOTES@NOTE3;RETAINER NOTES FOR TFR@NOTE4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("004- Add Claim:New claimant-Individual")]
        [NUnit.Framework.CategoryAttribute("US199848")]
        public virtual void _004_AddClaimNewClaimant_Individual()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("004- Add Claim:New claimant-Individual", new string[] {
                        "US199848"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 57
 testRunner.When("I click on Add Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.Then("I see subheader as \'Add Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.Then("I input case/debtor details as \'CASE # / DEBTOR NAME@12-22319 / MIGU;CATEGORY@Cre" +
                    "ditor;CLAIM #@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
    testRunner.When("I select Participant Type as \'New Claimant\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.When("I select Participant Type as \'Individual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("I input details as \'TITLE@Miss;FIRST NAME@PAUL;MIDDLE NAME@KEVIN;LAST NAME@BR;GEN" +
                    "DER@Male;STATE BAR ID@56780;SSN@123-45-6789;DRIVER\'S LICENSE@9898123456\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.And("I input Contact details as \'EMAIL@aeries123gmail.com;Address@TELANGANA;PHONE@9912" +
                    "053369;City@Chennai;State / Province@AL;Zip@500055\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.Then("I input codesvalues information \'STATUS@Superseded;OBJECTION CODE@Allow as Tardy;" +
                    "UTC CODE@2300 Bond Payments\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
 testRunner.Then("I input codesvalues Amounts information \'SCHEDULED AMOUNT@1000;CLAIMED AMOUNT@200" +
                    "0;ALLOWED AMOUNT@3000;RESERVED AMOUNT@4000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
 testRunner.Then("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@123456;CHE" +
                    "CK DESCRIPTION@DESCRPTION;DATE FILED@01/30/19;AMENDS@ADDCLAIM;VERSION@12;AMENDED" +
                    " BY@ADDCLAIM;AMENDED VERSION@20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@ADDCLAIM;INTERNAL CLAIM NOTE@ADDC" +
                    "LAIM;OBJECTION NOTES@ADDCLAIM;RETAINER NOTES FOR TFR@ADDCLAIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("005- Add Claim:New claimant-Corporation")]
        [NUnit.Framework.CategoryAttribute("US199848")]
        public virtual void _005_AddClaimNewClaimant_Corporation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("005- Add Claim:New claimant-Corporation", new string[] {
                        "US199848"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.When("I click on Add Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.Then("I see subheader as \'Add Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.Then("I input case/debtor details as \'CASE # / DEBTOR NAME@12-22319 / MIGU;CATEGORY@Wag" +
                    "e Claim;CLAIM #@555\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 78
    testRunner.When("I select Participant Type as \'New Claimant\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.When("I select Participant Type as \'Corporation\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("I input details as \'DISPLAY NAME@LOUIS;STATE BAR ID@12345;TAX ID@12-3456789\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.Then("I input Contact details as \'EMAIL@aeries123@gmail.com;Address@Mumbai;PHONE@950561" +
                    "6939;City@Mumbai;State / Province@AL;Zip@507111\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.Then("I input codesvalues information \'STATUS@Valid To Pay;OBJECTION CODE@Duplicate;UTC" +
                    " CODE@2100 Other Trustee\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
 testRunner.Then("I input codesvalues Amounts information \'SCHEDULED AMOUNT@900;CLAIMED AMOUNT@100;" +
                    "ALLOWED AMOUNT@200;RESERVED AMOUNT@600\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.Then("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@123456;CHE" +
                    "CK DESCRIPTION@DESCRPTION;DATE FILED@01/30/19;AMENDS@TEST;VERSION@13;AMENDED BY@" +
                    "TEST;AMENDED VERSION@14\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
 testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@NEWCLAIM;INTERNAL CLAIM NOTE@NEWC" +
                    "LAIM;OBJECTION NOTES@NEWCLAIM;RETAINER NOTES FOR TFR@NEWCLAIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("006- Edit Claim")]
        [NUnit.Framework.CategoryAttribute("US219897")]
        public virtual void _006_EditClaim()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("006- Edit Claim", new string[] {
                        "US219897"});
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.When("I click on Edit Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
    testRunner.Then("I input case/debtor details as \'CATEGORY@Investor;CLAIM #@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.Then("I input codesvalues information \'STATUS@Withdrawn;OBJECTION CODE@Allow as Tardy;U" +
                    "TC CODE@3711 Appraiser forTrustee Fees\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 96
 testRunner.Then("I input codesvalues Amounts information \'SCHEDULED AMOUNT@5000;CLAIMED AMOUNT@100" +
                    "0;ALLOWED AMOUNT@2000;RESERVED AMOUNT@6000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
 testRunner.Then("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@90876;CHEC" +
                    "K DESCRIPTION@editclaim;DATE FILED@01/30/19;AMENDS@editclaim;VERSION@10;AMENDED " +
                    "BY@editclaim;AMENDED VERSION@11\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 98
 testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@editclaim;INTERNAL CLAIM NOTE@edi" +
                    "tclaim;OBJECTION NOTES@editclaim;RETAINER NOTES FOR TFR@editclaim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 101
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("007- Claims:Case Level-Claims ADD")]
        [NUnit.Framework.CategoryAttribute("US217825")]
        public virtual void _007_ClaimsCaseLevel_ClaimsADD()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("007- Claims:Case Level-Claims ADD", new string[] {
                        "US217825"});
#line 104
this.ScenarioSetup(scenarioInfo);
#line 105
testRunner.Given("I enter to Unity Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 106
testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
       testRunner.When("I Enter \'99-11188\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
          testRunner.And("I Click on the Case Result \'99-11188\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
        testRunner.Then("verify the count on Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
          testRunner.When("I click on Add Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
           testRunner.Then("I input case/debtor details as \'CASE # / DEBTOR NAME@12-22319 / MIGU;CATEGORY@Wag" +
                    "e Claim;CLAIM #@555\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
        testRunner.When("I select Participant Type as \'New Claimant\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
     testRunner.And("I select Participant Type as \'Corporation\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
       testRunner.Then("I input Display name as \'LOUIS9100\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
          testRunner.Then("I input details as \'STATE BAR ID@12345;TAX ID@12-3456789\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 117
   testRunner.And("I input Contact details as \'EMAIL@aeries123@gmail.com;Address@Mumbai;PHONE@950561" +
                    "6939;City@Mumbai;Zip@507111\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
   testRunner.And("I enter state as \'AL\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
          testRunner.And("I input codesvalues information \'STATUS@Valid To Pay;OBJECTION CODE@Duplicate;UTC" +
                    " CODE@2100 Other Trustee\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
    testRunner.And("I input codesvalues Amounts information \'SCHEDULED AMOUNT@900;CLAIMED AMOUNT@100;" +
                    "ALLOWED AMOUNT@200;RESERVED AMOUNT@600\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
    testRunner.And("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@123456;CHE" +
                    "CK DESCRIPTION@DESCRPTION;DATE FILED@01/30/19;AMENDS@TEST;VERSION@13;AMENDED BY@" +
                    "TEST;AMENDED VERSION@14\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
    testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
          testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@new claim;INTERNAL CLAIM NOTE@new" +
                    " claim;OBJECTION NOTES@new claim;RETAINER NOTES FOR TFR@new claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
   testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 125
   testRunner.Then("verify the after count on Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 126
   testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("008- Claims:Case Level-Claims Edit")]
        [NUnit.Framework.CategoryAttribute("US217826")]
        public virtual void _008_ClaimsCaseLevel_ClaimsEdit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("008- Claims:Case Level-Claims Edit", new string[] {
                        "US217826"});
#line 129
this.ScenarioSetup(scenarioInfo);
#line 130
testRunner.Given("I enter to Unity Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 131
testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
       testRunner.When("I Enter \'17-90000\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 134
          testRunner.And("I Click on the Case Result \'17-90000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
          testRunner.When("I click on Edit Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
             testRunner.Then("I input case/debtor details as \'CATEGORY@Investor;CLAIM #@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
             testRunner.Then("I input codesvalues information \'STATUS@Withdrawn;OBJECTION CODE@Allow as Tardy;U" +
                    "TC CODE@3711 Appraiser forTrustee Fees\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
       testRunner.Then("I input codesvalues Amounts information \'SCHEDULED AMOUNT@5000;CLAIMED AMOUNT@100" +
                    "0;ALLOWED AMOUNT@2000;RESERVED AMOUNT@6000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 139
       testRunner.Then("I input Payment Options & Additional Creditor Info \'CREDITOR ACCOUNT #@90876;CHEC" +
                    "K DESCRIPTION@editclaim;DATE FILED@01/30/19;AMENDS@editclaim;VERSION@10;AMENDED " +
                    "BY@editclaim;AMENDED VERSION@11\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
       testRunner.And("I input Payment Options & Additional Creditor Checkboxes info \'Non-Compensible@YE" +
                    "S;Exclude From UFR@YES;Non-discharged@YES;Reaffirmed@YES\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
             testRunner.And("I input Notes information \'CLAIMS REGISTER NOTE@editclaim;INTERNAL CLAIM NOTE@edi" +
                    "tclaim;OBJECTION NOTES@editclaim;RETAINER NOTES FOR TFR@editclaim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
       testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
         testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("009_Claims - SaveInLineEdit and Verify")]
        [NUnit.Framework.CategoryAttribute("US235859")]
        public virtual void _009_Claims_SaveInLineEditAndVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("009_Claims - SaveInLineEdit and Verify", new string[] {
                        "US235859"});
#line 146
this.ScenarioSetup(scenarioInfo);
#line 147
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 148
 testRunner.And("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.When("I enter Creditor \'JEANNE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("I click on Arrow Icon to see all sections", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.Then("I edit \'CLAIMED\', \'13\', \'60000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 153
 testRunner.And("I edit \'ALLOWED\', \'14\', \'20000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.And("I edit \'SEQUENCE\', \'11\', \'75\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.Then("the \'CLAIMED\', \'13\' should contain \'$60,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 159
 testRunner.And("the \'ALLOWED\', \'14\' should contain \'$20,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("010_Claims - CancelInLineEdit and Verify")]
        [NUnit.Framework.CategoryAttribute("US235859")]
        public virtual void _010_Claims_CancelInLineEditAndVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("010_Claims - CancelInLineEdit and Verify", new string[] {
                        "US235859"});
#line 167
this.ScenarioSetup(scenarioInfo);
#line 168
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.And("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.When("I enter Creditor \'JEANNE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 171
 testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.Then("I edit the \'CLAIMED\', \'13\', \'67890\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 173
 testRunner.And("I edit the \'ALLOWED\', \'14\', \'34560\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("I edit the \'CLAIM #\', \'5\', \'345\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.And("I edit the \'SEQUENCE\', \'11\', \'69\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And("I edit the \'SCHEDULED\', \'0\', \'34000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I edit the \'RESERVED\', \'0\', \'12345\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.Then("the \'CLAIMED\', \'13\' should contain \'$60,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 179
 testRunner.And("the \'ALLOWED\', \'14\' should contain \'$20,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("the \'CLAIM #\', contains \'55\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("the \'SEQUENCE\', contains \'75\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("012_Claims - Export List Cancel Verification-Export Permission")]
        [NUnit.Framework.CategoryAttribute("US235859")]
        [NUnit.Framework.CategoryAttribute("US255998")]
        [NUnit.Framework.CategoryAttribute("US255998")]
        [NUnit.Framework.CategoryAttribute("US264012")]
        public virtual void _012_Claims_ExportListCancelVerification_ExportPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("012_Claims - Export List Cancel Verification-Export Permission", new string[] {
                        "US235859",
                        "US255998",
                        "US255998",
                        "US264012"});
#line 197
this.ScenarioSetup(scenarioInfo);
#line 198
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 199
  testRunner.When("I click On the EXPORT BUTTON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 200
  testRunner.Then("Validate the Text in the pop up.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 201
  testRunner.And("Click on the CANCEL BUTTON on the pop up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
  testRunner.And("I validate the Pop Up is not appearaing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
  testRunner.And("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("013_Claim - EXPORT List button Disabled-View Permission")]
        [NUnit.Framework.CategoryAttribute("US255998")]
        [NUnit.Framework.CategoryAttribute("US227039")]
        [NUnit.Framework.CategoryAttribute("US256009")]
        [NUnit.Framework.CategoryAttribute("US249370")]
        [NUnit.Framework.CategoryAttribute("US266867")]
        [NUnit.Framework.CategoryAttribute("US266866")]
        public virtual void _013_Claim_EXPORTListButtonDisabled_ViewPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("013_Claim - EXPORT List button Disabled-View Permission", new string[] {
                        "US255998",
                        "US227039",
                        "US256009",
                        "US249370",
                        "US266867",
                        "US266866"});
#line 206
this.ScenarioSetup(scenarioInfo);
#line 207
  testRunner.Given("I enter to Unity Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 208
  testRunner.Given("I enter to Claims page as user vandita1 with password Welcome444Epiq! and office " +
                    "crose", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 209
  testRunner.Then("Validate that export button is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 210
  testRunner.And("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("014 - Claim Page-Delete funtionality verification in Claim page")]
        [NUnit.Framework.CategoryAttribute("US256011")]
        public virtual void _014_ClaimPage_DeleteFuntionalityVerificationInClaimPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("014 - Claim Page-Delete funtionality verification in Claim page", new string[] {
                        "US256011"});
#line 213
this.ScenarioSetup(scenarioInfo);
#line 214
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 215
  testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
  testRunner.When("I Enter \'17-90000\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
  testRunner.And("I Click on the Case Result \'17-90000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
  testRunner.And("I can select all option in the header", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
  testRunner.And("I can Deselect all option in the header", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
     testRunner.And("I can select first record in dso page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
  testRunner.Then("I can click on delete button in the Claims Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 222
  testRunner.Then("verify the Text in the pop up as \'Cannot delete if any selected claim has linked " +
                    "payments. Select claims without payments and try again.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 223
  testRunner.And("I click on Delete button in pop up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 224
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("015 - Claim Page-Delete funtionality verification in Claim page with out selectin" +
            "g the record")]
        [NUnit.Framework.CategoryAttribute("US256011")]
        public virtual void _015_ClaimPage_DeleteFuntionalityVerificationInClaimPageWithOutSelectingTheRecord()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("015 - Claim Page-Delete funtionality verification in Claim page with out selectin" +
                    "g the record", new string[] {
                        "US256011"});
#line 227
this.ScenarioSetup(scenarioInfo);
#line 228
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 229
  testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
  testRunner.When("I Enter \'17-90000\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
  testRunner.And("I Click on the Case Result \'17-90000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
  testRunner.And("I can see delete button is not clickcable until select the case", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("016 - Claim Page-Cancel funtionality verification in Claim page")]
        [NUnit.Framework.CategoryAttribute("US256011")]
        public virtual void _016_ClaimPage_CancelFuntionalityVerificationInClaimPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("016 - Claim Page-Cancel funtionality verification in Claim page", new string[] {
                        "US256011"});
#line 236
this.ScenarioSetup(scenarioInfo);
#line 237
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 238
     testRunner.And("I can select first record in Claim page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
  testRunner.Then("I can click on delete button in the Claim Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 240
  testRunner.Then("verify the Text in the pop up as \'Confirm that you want to delete the selected cl" +
                    "aims.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 241
  testRunner.And("I click on Cancel button in pop up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 242
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("017 - Claim Page-View Payments Linked to Claim - On Claim List")]
        [NUnit.Framework.CategoryAttribute("US256006")]
        [NUnit.Framework.CategoryAttribute("US247346")]
        public virtual void _017_ClaimPage_ViewPaymentsLinkedToClaim_OnClaimList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("017 - Claim Page-View Payments Linked to Claim - On Claim List", new string[] {
                        "US256006",
                        "US247346"});
#line 245
this.ScenarioSetup(scenarioInfo);
#line 246
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 247
  testRunner.When("I click on PAID column \'$0.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 248
  testRunner.Then("verify the label \'Transactions Linked to Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 249
  testRunner.Then("verify the columns from \'3\' to \'7\' displayed on \'modal-body\' as \'ACCOUNT #;TYPE;D" +
                    "ATE;NAME;AMOUNT\' in Transactions Linked to Claim page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 250
  testRunner.Then("verify the notification message \'No transactions linked to this claim.\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 251
     testRunner.Then("I click \'CLOSE\' Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 252
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("018 - Claim Page-View Payments Linked to Claim - On Claim List")]
        [NUnit.Framework.CategoryAttribute("US256006")]
        [NUnit.Framework.CategoryAttribute("US247346")]
        public virtual void _018_ClaimPage_ViewPaymentsLinkedToClaim_OnClaimList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("018 - Claim Page-View Payments Linked to Claim - On Claim List", new string[] {
                        "US256006",
                        "US247346"});
#line 255
this.ScenarioSetup(scenarioInfo);
#line 256
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 257
  testRunner.When("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 258
  testRunner.When("I enter Creditor \'BERNHEIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 259
  testRunner.And("I select Class \'Secured\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
  testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
  testRunner.When("I click on PAID column \'$120,000,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 262
  testRunner.Then("verify the label \'Transactions Linked to Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 263
  testRunner.Then("verify the columns from \'3\' to \'7\' displayed on \'modal-body\' as \'ACCOUNT #;TYPE;D" +
                    "ATE;NAME;AMOUNT\' in Transactions Linked to Claim page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 264
  testRunner.Then("click on expand symbol and verify the columns as \'BANK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 265
     testRunner.Then("I click \'CLOSE\' Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 266
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("019 - Claim Page-View Payments Linked to Claim - On Edit Claim List")]
        [NUnit.Framework.CategoryAttribute("US256008")]
        [NUnit.Framework.CategoryAttribute("US249367")]
        public virtual void _019_ClaimPage_ViewPaymentsLinkedToClaim_OnEditClaimList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("019 - Claim Page-View Payments Linked to Claim - On Edit Claim List", new string[] {
                        "US256008",
                        "US249367"});
#line 269
this.ScenarioSetup(scenarioInfo);
#line 270
  testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 271
  testRunner.When("I click on filter button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 272
  testRunner.When("I enter Creditor \'BERNHEIM\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 273
  testRunner.And("I select Class \'Secured\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
  testRunner.And("I click on close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 275
  testRunner.When("I click on PAID column \'$120,000,000.00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 276
  testRunner.Then("verify the label \'Transactions Linked to Claim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 277
  testRunner.Then("verify the columns from \'3\' to \'7\' displayed on \'modal-body\' as \'ACCOUNT #;TYPE;D" +
                    "ATE;NAME;AMOUNT\' in Transactions Linked to Claim page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 278
  testRunner.Then("\'AMOUNT\' should be able sorted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 279
  testRunner.Then("click on expand symbol and verify the columns as \'BANK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 280
     testRunner.Then("I click \'CLOSE\' Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 281
  testRunner.Then("click Edit Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 282
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("020 - Schedule to Claim Reconciliation Page-All Cases")]
        [NUnit.Framework.CategoryAttribute("US259310")]
        public virtual void _020_ScheduleToClaimReconciliationPage_AllCases()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("020 - Schedule to Claim Reconciliation Page-All Cases", new string[] {
                        "US259310"});
#line 285
this.ScenarioSetup(scenarioInfo);
#line 286
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 287
  testRunner.Then("verify the page header \'Schedule to Claim Management\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 288
  testRunner.Then("Schedule to Claim Management Breadcrumbs should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 289
  testRunner.Then("I see the fields in Schedule to Claim Management page as CaseNumber \'CASE #\', Deb" +
                    "tor \'DEBTOR\', Claims \'CLAIMS\',Schedules \'SCHEDULES\',Unreconciled \'UNRECONCILED\'," +
                    "Status \'STATUS\',Case \'CASE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 290
  testRunner.Then("verify the Schedule to Claim Management page UI count", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 291
  testRunner.Then("verify the Schedule to Claim Management page count from Database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 292
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("021 - Schedule to Claim Reconciliation Page-Specific Case")]
        [NUnit.Framework.CategoryAttribute("US259310")]
        public virtual void _021_ScheduleToClaimReconciliationPage_SpecificCase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("021 - Schedule to Claim Reconciliation Page-Specific Case", new string[] {
                        "US259310"});
#line 295
this.ScenarioSetup(scenarioInfo);
#line 296
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 297
  testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
  testRunner.When("I Enter \'01-21039\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 299
     testRunner.And("I Click on the Case Result \'01-21039\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.Then("Schedule to Claim Management Breadcrumbs should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 301
    testRunner.Then("I see the fields in Schedule to Claim Management page as CaseNumber \'CASE #\', Deb" +
                    "tor \'DEBTOR\', Claims \'CLAIMS\',Schedules \'SCHEDULES\',Unreconciled \'UNRECONCILED\'," +
                    "Status \'STATUS\',Case \'CASE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 302
    testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("022 - Schedule to Claim Reconciliation Page- Filter options")]
        [NUnit.Framework.CategoryAttribute("US259310")]
        public virtual void _022_ScheduleToClaimReconciliationPage_FilterOptions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("022 - Schedule to Claim Reconciliation Page- Filter options", new string[] {
                        "US259310"});
#line 305
this.ScenarioSetup(scenarioInfo);
#line 306
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 307
  testRunner.And("I click on filter in Schedule to Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 308
  testRunner.Then("I verify default data in filter options as AllClaimsReconciled \'No\', AssetStatus " +
                    "\'Asset\', CaseStaus \'All\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 309
  testRunner.Then("I verify data in filter options in Schedule to Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 310
  testRunner.Then("I select  AllClaimsReconciled \'Yes\', AssetStatus \'All\', CaseStaus \'Open\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 311
  testRunner.Then("I verify Table Header when AllClaimsReconciled \'Yes\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 312
  testRunner.Then("I verify Table Header when AllClaimsReconciled as \'No\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 313
  testRunner.Then("I verify message when there are no results to display in the grid \'No results to " +
                    "display per selections\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 314
  testRunner.Then("I click Reset in filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 315
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("023 - Schedule to Claim Reconciliation Page- Without Permissions - All cases")]
        [NUnit.Framework.CategoryAttribute("US259310")]
        public virtual void _023_ScheduleToClaimReconciliationPage_WithoutPermissions_AllCases()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("023 - Schedule to Claim Reconciliation Page- Without Permissions - All cases", new string[] {
                        "US259310"});
#line 318
this.ScenarioSetup(scenarioInfo);
#line 319
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as user AutomationView2 with pas" +
                    "sword Welcome123Epiq! and office crose", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 320
  testRunner.Then("I verify message \'Please contact your Office Administrator and request permission" +
                    " to view this content. You are missing one of the following permissions: Schedul" +
                    "es Reconcile\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 321
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("024 - Schedule to Claim Reconciliation Page- Without Permissions - Specific case")]
        [NUnit.Framework.CategoryAttribute("US259310")]
        public virtual void _024_ScheduleToClaimReconciliationPage_WithoutPermissions_SpecificCase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("024 - Schedule to Claim Reconciliation Page- Without Permissions - Specific case", new string[] {
                        "US259310"});
#line 324
this.ScenarioSetup(scenarioInfo);
#line 325
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as user AutomationView2 with pas" +
                    "sword Welcome123Epiq! and office crose", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 326
  testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
  testRunner.When("I Enter \'01-21039\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 328
     testRunner.And("I Click on the Case Result \'01-21039\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 329
  testRunner.Then("I verify message \'Please contact your Office Administrator and request permission" +
                    " to view this content. You are missing one of the following permissions: Schedul" +
                    "es Reconcile\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 330
  testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("026- Claims:Case Level-Claims Edit- Delete Document")]
        [NUnit.Framework.CategoryAttribute("US266866")]
        [NUnit.Framework.CategoryAttribute("US#266865")]
        [NUnit.Framework.CategoryAttribute("US#273999")]
        [NUnit.Framework.CategoryAttribute("US#270469")]
        [NUnit.Framework.CategoryAttribute("US266867")]
        [NUnit.Framework.CategoryAttribute("US#266865")]
        public virtual void _026_ClaimsCaseLevel_ClaimsEdit_DeleteDocument()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("026- Claims:Case Level-Claims Edit- Delete Document", new string[] {
                        "US266866",
                        "US#266865",
                        "US#273999",
                        "US#270469",
                        "US266867",
                        "US#266865"});
#line 349
this.ScenarioSetup(scenarioInfo);
#line 350
 testRunner.Given("I enter to Unity Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 351
 testRunner.Given("I enter to Claims page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 352
 testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 353
 testRunner.When("I Enter \'17-90000\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 354
 testRunner.And("I Click on the Case Result \'17-90000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 355
 testRunner.When("I click on Edit Claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 356
 testRunner.And("I click on delete button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 357
 testRunner.When("I save claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 358
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("027 - Schedule to Claim Reconciliation Page- Reconcilation")]
        [NUnit.Framework.CategoryAttribute("US#266884")]
        [NUnit.Framework.CategoryAttribute("US#266885")]
        public virtual void _027_ScheduleToClaimReconciliationPage_Reconcilation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("027 - Schedule to Claim Reconciliation Page- Reconcilation", new string[] {
                        "US#266884",
                        "US#266885"});
#line 361
this.ScenarioSetup(scenarioInfo);
#line 362
  testRunner.Given("I enter to Schedule to Claim Reconciliation page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 363
     testRunner.And("I see the Search box under All Cases Section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
  testRunner.When("I Enter \'01-21039\' On The Universal Search Section Input", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 365
     testRunner.And("I Click on the Case Result \'01-21039\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 366
  testRunner.And("I Click on Unreconciled option", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 367
  testRunner.When("I click on Filter on Banking Activity page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 368
     testRunner.Then("I click on close button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 369
  testRunner.When("I click on Radio Button of schedules and claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 370
  testRunner.And("I Add link and unlink transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
     testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("028 - Schedule to Claim Reconciliation Page- Link and Unlink Transactions")]
        [NUnit.Framework.CategoryAttribute("US266886")]
        public virtual void _028_ScheduleToClaimReconciliationPage_LinkAndUnlinkTransactions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("028 - Schedule to Claim Reconciliation Page- Link and Unlink Transactions", new string[] {
                        "US266886"});
#line 374
this.ScenarioSetup(scenarioInfo);
#line 375
 testRunner.Given("I enter to Schedule to Claim Reconciliation page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 376
 testRunner.Then("I click on Unreconciled link for case number \'01-21039\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 377
 testRunner.And("I select Schedules in Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 378
 testRunner.And("I verify Schedules Link button and X button at the bottom of the screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 379
 testRunner.And("I select Claims in Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 380
 testRunner.And("I verify Claims Link button and X button at the bottom of the screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 381
 testRunner.Then("I select schedule and claim in Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 382
 testRunner.And("I click LINK button in Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 383
 testRunner.And("I click UNLINK button in Claim Reconciliation page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 384
 testRunner.Then("I SignOut from the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
