// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Epiq.ETS.TCMS.Anywhere.Testing.E2ETest.Features.Cases.Detail.Banking.Summary
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Case Detail - Banking - Summary")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("DoNotExecute")]
    [NUnit.Framework.CategoryAttribute("BankingTransactions")]
    public partial class CaseDetail_Banking_SummaryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CaseBankingSummary.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Case Detail - Banking - Summary", "\tIn order to be able to enter future banking transactions\r\n\tAs a user of Unity\r\n\t" +
                    "I need to be able to navigate and see the Bank Accounts associated to each case", ProgrammingLanguage.CSharp, new string[] {
                        "Regression",
                        "Ignore",
                        "DoNotExecute",
                        "BankingTransactions"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("001 - Case Detail - Banking Tab - Sections Display (Desktop)")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("Sanity")]
        [NUnit.Framework.CategoryAttribute("CaseBankingSummary")]
        [NUnit.Framework.CategoryAttribute("US74626")]
        [NUnit.Framework.CategoryAttribute("TC77120")]
        [NUnit.Framework.CategoryAttribute("US97749")]
        [NUnit.Framework.CategoryAttribute("TC100834")]
        [NUnit.Framework.CategoryAttribute("US98816")]
        [NUnit.Framework.CategoryAttribute("TC100816")]
        public virtual void _001_CaseDetail_BankingTab_SectionsDisplayDesktop()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("001 - Case Detail - Banking Tab - Sections Display (Desktop)", new string[] {
                        "CaseDetail",
                        "Sanity",
                        "CaseBankingSummary",
                        "US74626",
                        "TC77120",
                        "US97749",
                        "TC100834",
                        "US98816",
                        "TC100816"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.Then("I See Banking Detail Page Displays and Tab Title is \'Banking Detail\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.And("I See the Banking Summary Section With Title \'Banking Summary\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("I See the Bank Account Summary Section With Title \'Account Summary\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("I See the Ledger Section With Title \'Ledger Summary\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("002 - Case Detail - Banking Summary - No Bank Accounts")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("Sanity")]
        [NUnit.Framework.CategoryAttribute("CaseClaimsSummary")]
        [NUnit.Framework.CategoryAttribute("US74626")]
        [NUnit.Framework.CategoryAttribute("TC77122")]
        public virtual void _002_CaseDetail_BankingSummary_NoBankAccounts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("002 - Case Detail - Banking Summary - No Bank Accounts", new string[] {
                        "CaseDetail",
                        "Sanity",
                        "CaseClaimsSummary",
                        "US74626",
                        "TC77122"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'0:000-XXX\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("I See No Banking Summary Items And a Message Shows Reading \'No Results Available\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("003 - Case Detail - Banking Summary - Cards Content And Selection")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("Sanity")]
        [NUnit.Framework.CategoryAttribute("CaseClaimsSummary")]
        [NUnit.Framework.CategoryAttribute("US74626")]
        [NUnit.Framework.CategoryAttribute("TC77121")]
        [NUnit.Framework.CategoryAttribute("US36857")]
        [NUnit.Framework.CategoryAttribute("TC77863")]
        [NUnit.Framework.CategoryAttribute("US97706")]
        [NUnit.Framework.CategoryAttribute("TC98697")]
        [NUnit.Framework.CategoryAttribute("RegressionFixesIt34")]
        public virtual void _003_CaseDetail_BankingSummary_CardsContentAndSelection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("003 - Case Detail - Banking Summary - Cards Content And Selection", new string[] {
                        "CaseDetail",
                        "Sanity",
                        "CaseClaimsSummary",
                        "US74626",
                        "TC77121",
                        "US36857",
                        "TC77863",
                        "US97706",
                        "TC98697",
                        "RegressionFixesIt34"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'11-29627\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "BankAccountName",
                        "Status",
                        "BankAccountNumber",
                        "BankName",
                        "Ledger",
                        "Bank"});
            table1.AddRow(new string[] {
                        "Checking - Non Interest",
                        "OPEN",
                        "9999974139",
                        "EagleBank",
                        "$9,291.88",
                        "$11,129.88"});
            table1.AddRow(new string[] {
                        "Money Market - Interest Bearing",
                        "OPEN",
                        "9999924076",
                        "Bank of America",
                        "$12,952.12",
                        "$0.00"});
#line 43
 testRunner.Then("I See Banking Summary Cards and All Values are Correct", ((string)(null)), table1, "Then ");
#line 48
 testRunner.And("First Card is Selected By Default And Selecting Each Card Displays BA Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("004 - Case Detail - Banking Summary - Negative Values")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("Sanity")]
        [NUnit.Framework.CategoryAttribute("CaseClaimsSummary")]
        [NUnit.Framework.CategoryAttribute("US36857")]
        [NUnit.Framework.CategoryAttribute("TC77862")]
        [NUnit.Framework.CategoryAttribute("RegressionFixesIt34")]
        public virtual void _004_CaseDetail_BankingSummary_NegativeValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("004 - Case Detail - Banking Summary - Negative Values", new string[] {
                        "CaseDetail",
                        "Sanity",
                        "CaseClaimsSummary",
                        "US36857",
                        "TC77862",
                        "RegressionFixesIt34"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'09-13569\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "BankAccountName",
                        "Status",
                        "BankAccountNumber",
                        "BankName",
                        "Ledger",
                        "Bank"});
            table2.AddRow(new string[] {
                        "Checking - Non Interest",
                        "OPEN",
                        "9999974127",
                        "EagleBank",
                        "-$1,015.89",
                        "$409.16"});
#line 58
 testRunner.Then("I See Banking Summary Cards and All Values are Correct", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("005 - Case Detail - Banking Summary - Navigate Back to Claims Detail")]
        [NUnit.Framework.CategoryAttribute("CaseDetail")]
        [NUnit.Framework.CategoryAttribute("Sanity")]
        [NUnit.Framework.CategoryAttribute("CaseBankingSummary")]
        [NUnit.Framework.CategoryAttribute("US74626")]
        [NUnit.Framework.CategoryAttribute("TC98515")]
        public virtual void _005_CaseDetail_BankingSummary_NavigateBackToClaimsDetail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("005 - Case Detail - Banking Summary - Navigate Back to Claims Detail", new string[] {
                        "CaseDetail",
                        "Sanity",
                        "CaseBankingSummary",
                        "US74626",
                        "TC98515"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("I enter to 341 Meeting page as superuser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
 testRunner.And("I Enter to Case Detail page for Case with Case Number \'06-15658\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I Go to Banking Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("I Go to Claims Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.Then("I See Claims Detail is Selected by Default and Tab Title is \'Claims Detail\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
